<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Embeddings – Agentic AI Engineering Study Book</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../phase-02-llm-fundamentals/08-context-windows-and-kv-cache.html" rel="next">
<link href="../phase-02-llm-fundamentals/06-tokenization-and-tokens.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-89355393b13d2c35defd37e977706fc2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-54623c61267def5306c3b17f0a722ca1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../assets/fonts/fonts.css">
<link rel="stylesheet" href="../styles/custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/index.html">Phase 2 — LLM and Generative AI Fundamentals</a></li><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/07-embeddings.html"><span class="chapter-title">Embeddings</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Agentic AI Engineering Study Book</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Study architecture</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-01-production-python/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 — Production Python</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/01-type-hints.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Type Hints</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/02-dataclasses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dataclasses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/03-pydantic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pydantic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/04-decorators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Decorators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/05-iterators-and-generators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Iterators and Generators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/06-context-managers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Managers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/07-exception-handling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Exception Handling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/08-file-handling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">File Handling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/09-async-and-asyncio.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Async and asyncio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/10-threads-and-processes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Threads and Processes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/11-concurrency-patterns.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Concurrency Patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/12-packaging-and-virtual-environments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Packaging and Virtual Environments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/13-dependency-management.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dependency Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/14-logging.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/15-configuration-management.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Configuration Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/16-pytest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">pytest</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/17-mocking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mocking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/18-profiling-and-performance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Profiling and Performance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/19-fastapi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">FastAPI</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/20-sqlalchemy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">SQLAlchemy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/21-alembic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Alembic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/22-postgresql.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">PostgreSQL</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/23-redis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Redis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/24-authentication-and-authorization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Authentication and Authorization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/25-background-jobs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Background Jobs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/26-rate-limiting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Rate Limiting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/27-api-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">API Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/28-dockerizing-python-applications.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dockerizing Python Applications</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/29-cicd-for-python-services.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">CI/CD for Python Services</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-02-llm-fundamentals/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 2 — LLM and Generative AI Fundamentals</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/01-how-ml-and-neural-networks-work.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How Machine Learning and Neural Networks Work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/02-tensors-and-pytorch.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tensors and PyTorch</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/03-forward-pass-and-backpropagation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Forward Pass and Backpropagation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/04-attention-and-self-attention.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Attention and Self-Attention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/05-the-transformer-architecture.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Transformer Architecture</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/06-tokenization-and-tokens.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tokenization and Tokens</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/07-embeddings.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Embeddings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/08-context-windows-and-kv-cache.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Windows and the KV Cache</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/09-logits-softmax-next-token-prediction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logits, Softmax, and Next-Token Prediction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/10-sampling-temperature-top-k-top-p.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sampling: Temperature, Top-K, Top-P</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/11-training-vs-inference-and-batching.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Training vs Inference and Batching</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/12-pretraining-finetuning-instruction-tuning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pretraining, Fine-Tuning, and Instruction Tuning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/13-rlhf-and-preference-alignment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RLHF and Preference Alignment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/14-lora-qlora-peft.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Parameter-Efficient Fine-Tuning: LoRA, QLoRA, PEFT</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/15-numeric-precision-and-quantization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Numeric Precision and Quantization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/16-structured-outputs-and-json-schema.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Structured Outputs and JSON Schema</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/17-function-and-tool-calling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Function and Tool Calling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/18-streaming-responses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Streaming Responses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/19-prompt-design-and-system-prompts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Prompt Design and System Prompts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/20-context-engineering.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Engineering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/21-hallucinations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hallucinations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/22-prompt-injection-and-context-poisoning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Prompt Injection and Context Poisoning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/23-model-comparison-and-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Model Comparison and Selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/24-provider-apis-openai-anthropic-gemini.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Provider APIs: OpenAI, Anthropic, Gemini</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/25-open-source-models-and-hugging-face.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Open-Source Models and Hugging Face</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#why-this-exists" id="toc-why-this-exists" class="nav-link active" data-scroll-target="#why-this-exists">Why this exists</a></li>
  <li><a href="#start-from-zero" id="toc-start-from-zero" class="nav-link" data-scroll-target="#start-from-zero">Start from zero</a></li>
  <li><a href="#the-core-idea" id="toc-the-core-idea" class="nav-link" data-scroll-target="#the-core-idea">The core idea</a></li>
  <li><a href="#how-it-works" id="toc-how-it-works" class="nav-link" data-scroll-target="#how-it-works">How it works</a></li>
  <li><a href="#the-syntax-you-will-use" id="toc-the-syntax-you-will-use" class="nav-link" data-scroll-target="#the-syntax-you-will-use">The syntax you will use</a></li>
  <li><a href="#examples-simple-to-real" id="toc-examples-simple-to-real" class="nav-link" data-scroll-target="#examples-simple-to-real">Examples: simple to real</a></li>
  <li><a href="#in-production" id="toc-in-production" class="nav-link" data-scroll-target="#in-production">In production</a></li>
  <li><a href="#interview-questions" id="toc-interview-questions" class="nav-link" data-scroll-target="#interview-questions">Interview questions</a></li>
  <li><a href="#remember-this" id="toc-remember-this" class="nav-link" data-scroll-target="#remember-this">Remember this</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/index.html">Phase 2 — LLM and Generative AI Fundamentals</a></li><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/07-embeddings.html"><span class="chapter-title">Embeddings</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Embeddings</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Interview answer (say this first).</strong> An embedding is a learned vector of floating-point numbers that represents a token, word, sentence, or document. It replaces an arbitrary ID with a position in space, so that things with similar meaning end up close together. Embeddings are how a model turns discrete symbols into geometry it can do math on, and they are the same vectors that power semantic search and retrieval.</p>
</blockquote>
<section id="why-this-exists" class="level2">
<h2 class="anchored" data-anchor-id="why-this-exists">Why this exists</h2>
<p>A model receives token IDs. An ID is just a label: <code>"cat"</code> might be <code>9246</code> and <code>"dog"</code> might <code>3290</code>. Those numbers have no relationship to each other. If the model only ever saw IDs, it would have to learn from scratch that 9246 and 3290 are related, and it would have no way to say <em>how</em> related.</p>
<p>The first fix people tried is a <strong>one-hot vector</strong>. If the vocabulary has 50,000 tokens, token 9246 becomes a vector of 50,000 numbers that is all zeros except a 1 at position 9246.</p>
<pre class="text"><code># vocab size 5, for illustration
"cat"  -&gt; [0, 0, 1, 0, 0]
"dog"  -&gt; [0, 0, 0, 1, 0]
"car"  -&gt; [0, 0, 0, 0, 1]</code></pre>
<p>This is unambiguous, but it has two fatal problems:</p>
<ol type="1">
<li><strong>It is enormous.</strong> With a 100k vocabulary the vector has 100,000 numbers, almost all zero.</li>
<li><strong>Every pair is equally unrelated.</strong> The dot product of any two different one-hot vectors is exactly zero. <code>"cat"</code> is as unrelated to <code>"dog"</code> as it is to <code>"carburetor"</code>. There is no similarity to learn from.</li>
</ol>
<p>Embeddings solve both. Instead of a 100,000-dimension sparse vector, each token gets a short, dense vector of, say, 768 or 4096 learned numbers. Tokens used in similar contexts are pushed toward similar vectors during training, so the geometry itself carries meaning.</p>
<p>This is the idea that makes modern AI work: <strong>meaning becomes distance.</strong> Once meaning is distance, you can search by it, cluster by it, and let the model do arithmetic on it.</p>
</section>
<section id="start-from-zero" class="level2">
<h2 class="anchored" data-anchor-id="start-from-zero">Start from zero</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Word</th>
<th>Plain meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Vector</strong></td>
<td>An ordered list of numbers, like <code>[0.2, -0.5, 1.1]</code>.</td>
</tr>
<tr class="even">
<td><strong>Dimension</strong></td>
<td>How many numbers are in the vector. Written <code>D</code>.</td>
</tr>
<tr class="odd">
<td><strong>Dense</strong></td>
<td>Most numbers are non-zero. Embeddings are dense.</td>
</tr>
<tr class="even">
<td><strong>Sparse</strong></td>
<td>Most numbers are zero. One-hot vectors are sparse.</td>
</tr>
<tr class="odd">
<td><strong>One-hot</strong></td>
<td>A vector of all zeros with a single 1 marking one category.</td>
</tr>
<tr class="even">
<td><strong>Embedding</strong></td>
<td>A dense vector learned to represent an item. Also the act of producing it.</td>
</tr>
<tr class="odd">
<td><strong>Embedding matrix</strong></td>
<td>The table of shape <code>vocab_size × dimension</code> holding one row per token. Written <code>E</code>.</td>
</tr>
<tr class="even">
<td><strong>Embedding model</strong></td>
<td>A model that turns text into a vector, used for search, clustering, and retrieval.</td>
</tr>
<tr class="odd">
<td><strong>Dot product</strong></td>
<td>Multiply matching entries and add them: <code>sum(a[i] * b[i])</code>. Measures alignment.</td>
</tr>
<tr class="even">
<td><strong>Norm / magnitude</strong></td>
<td>The length of a vector: <code>sqrt(sum(x[i] ** 2))</code>.</td>
</tr>
<tr class="odd">
<td><strong>Cosine similarity</strong></td>
<td>Dot product divided by both norms. Measures the angle between vectors, ignoring length.</td>
</tr>
<tr class="even">
<td><strong>Static embedding</strong></td>
<td>One fixed vector per word, regardless of context.</td>
</tr>
<tr class="odd">
<td><strong>Contextual embedding</strong></td>
<td>A vector for a token that changes with the surrounding text.</td>
</tr>
<tr class="even">
<td><strong>Nearest neighbour</strong></td>
<td>The stored vector with the highest similarity to a query vector.</td>
</tr>
<tr class="odd">
<td><strong>Vector search / ANN</strong></td>
<td>Finding nearest neighbours efficiently in a large vector collection.</td>
</tr>
<tr class="even">
<td><strong>Vector database</strong></td>
<td>A store built for vector search, like pgvector, FAISS, or Qdrant.</td>
</tr>
</tbody>
</table>
<p>Two ideas cause most confusion, so separate them now:</p>
<ul>
<li><strong>Similarity is about direction, not length.</strong> Two vectors pointing the same way are similar even if one is ten times longer. Cosine similarity deliberately ignores length.</li>
<li><strong>Static vs contextual is about when the vector is fixed.</strong> A word’s <em>initial</em> embedding is static; the model then transforms it using context, producing a contextual vector.</li>
</ul>
</section>
<section id="the-core-idea" class="level2">
<h2 class="anchored" data-anchor-id="the-core-idea">The core idea</h2>
<p>Imagine every word pinned to a point on a giant map. On this map, <code>"king"</code> is near <code>"queen"</code>, <code>"cat"</code> is near <code>"dog"</code>, and <code>"Paris"</code> is near <code>"France"</code>. The map has hundreds of dimensions, so you cannot draw it, but the idea is ordinary geography: nearby means similar.</p>
<p>The famous illustration is that the <em>directions</em> on this map capture relationships:</p>
<pre class="text"><code>vector("king") - vector("man") + vector("woman")  ≈  vector("queen")</code></pre>
<p>The “royalty” direction and the “gender” direction are consistent enough that adding and subtracting vectors moves you to sensible places. This is not a trick the engineers coded; it falls out of training on text.</p>
<p>Now the machine view. An embedding is implemented as a <strong>table lookup</strong>.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A["token ID&lt;br/&gt;3290"] --&gt; B["embedding matrix E&lt;br/&gt;vocab x dim"]
    B --&gt;|"select row 3290"| C["dense vector&lt;br/&gt;[0.2, -0.5, 1.1, ...]"]
    C --&gt; D["similarity search&lt;br/&gt;dot product / cosine"]
    D --&gt; E["nearest tokens&lt;br/&gt;dog, puppy, cat"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>That matrix is the model’s <strong>input</strong> embedding layer. A dedicated embedding model is a different component: it runs the whole text through a transformer and returns one pooled sentence vector for search, not a row from this table.</p>
<p>Here is the central comparison:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Property</th>
<th>One-hot</th>
<th>Embedding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Shape</td>
<td><code>vocab_size</code> (e.g.&nbsp;100,000)</td>
<td><code>dim</code> (e.g.&nbsp;768)</td>
</tr>
<tr class="even">
<td>Values</td>
<td>all 0 except one 1</td>
<td>mostly non-zero floats</td>
</tr>
<tr class="odd">
<td>Learns meaning?</td>
<td>No</td>
<td>Yes</td>
</tr>
<tr class="even">
<td>Similarity between tokens</td>
<td>always 0</td>
<td>meaningful</td>
</tr>
<tr class="odd">
<td>Lookup cost</td>
<td>none, it <em>is</em> the ID</td>
<td>one row read from a matrix</td>
</tr>
</tbody>
</table>
</section>
<section id="how-it-works" class="level2">
<h2 class="anchored" data-anchor-id="how-it-works">How it works</h2>
<ol type="1">
<li><strong>Fix a vocabulary and a dimension.</strong> Say <code>V = 100,000</code> tokens and <code>D = 768</code> dimensions. These are design choices, not learned.</li>
<li><strong>Create the embedding matrix <code>E</code>.</strong> It has shape <code>V × D</code>. Every token owns exactly one row.</li>
<li><strong>Initialise randomly.</strong> Small random values, so no two tokens start identical. This is the same symmetry-breaking as any neural network.</li>
<li><strong>Look up a token.</strong> Take its ID and read row <code>ID</code> from <code>E</code>. That is the whole “embedding layer”. It is a gather, not a multiplication.</li>
<li><strong>Train.</strong> Backpropagation sends a gradient to every row that appeared in the batch. Rows for tokens used in similar contexts receive similar nudges, so they drift together.</li>
<li><strong>Use similarity.</strong> Compare two vectors with the dot product or cosine similarity to score how related they are.</li>
<li><strong>Make embeddings contextual.</strong> A transformer takes the static rows, then mixes them with attention, so the vector for <code>"bank"</code> depends on whether the sentence is about rivers or money.</li>
<li><strong>Serve them.</strong> A dedicated embedding model returns vectors for documents; a vector database stores them and answers nearest-neighbour queries.</li>
</ol>
<p>The reason token embeddings and output predictions are often tied together: the final layer needs one score per vocabulary item, and the embedding matrix already has one vector per vocabulary item. Reusing it (<strong>weight tying</strong>) saves parameters and usually improves quality.</p>
</section>
<section id="the-syntax-you-will-use" class="level2">
<h2 class="anchored" data-anchor-id="the-syntax-you-will-use">The syntax you will use</h2>
<p><strong>Dot product and cosine similarity with numpy.</strong> These two functions are the heart of semantic comparison.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> np.array([<span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">3.0</span>])</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> np.array([<span class="fl">2.0</span>, <span class="fl">4.0</span>, <span class="fl">6.0</span>])</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>dot <span class="op">=</span> <span class="bu">float</span>(np.dot(a, b))                                  <span class="co"># 28.0</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>cos <span class="op">=</span> <span class="bu">float</span>(np.dot(a, b) <span class="op">/</span> (np.linalg.norm(a) <span class="op">*</span> np.linalg.norm(b)))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 1.0 — same direction, so maximum similarity</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>np.dot</code> measures alignment and grows with length. Dividing by both norms removes length, leaving only the angle.</p>
<p><strong>An embedding matrix and a lookup.</strong> The lookup is a row selection; a one-hot multiply is the same thing in matrix form.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>V, D <span class="op">=</span> <span class="dv">6</span>, <span class="dv">4</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>E <span class="op">=</span> rng.normal(size<span class="op">=</span>(V, D))          <span class="co"># 6 tokens, 4 dimensions</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>vocab <span class="op">=</span> [<span class="st">"cat"</span>, <span class="st">"dog"</span>, <span class="st">"kitten"</span>, <span class="st">"puppy"</span>, <span class="st">"car"</span>, <span class="st">"truck"</span>]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>word_to_id <span class="op">=</span> {w: i <span class="cf">for</span> i, w <span class="kw">in</span> <span class="bu">enumerate</span>(vocab)}</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>vector <span class="op">=</span> E[word_to_id[<span class="st">"dog"</span>]]         <span class="co"># shape (4,) — the row for "dog"</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>one_hot <span class="op">=</span> np.zeros(V)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>one_hot[word_to_id[<span class="st">"dog"</span>]] <span class="op">=</span> <span class="fl">1.0</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.allclose(one_hot <span class="op">@</span> E, E[word_to_id[<span class="st">"dog"</span>]])   <span class="co"># True</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>one_hot @ E</code> selects the row, which is why lookup is cheap.</p>
<p><strong>Ranking neighbours.</strong> Compute similarity to every row, then sort.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>q <span class="op">=</span> E[word_to_id[<span class="st">"cat"</span>]]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>sims <span class="op">=</span> E <span class="op">@</span> q <span class="op">/</span> (np.linalg.norm(E, axis<span class="op">=</span><span class="dv">1</span>) <span class="op">*</span> np.linalg.norm(q))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>best <span class="op">=</span> np.argsort(<span class="op">-</span>sims)              <span class="co"># indices from most to least similar</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>[vocab[i] <span class="cf">for</span> i <span class="kw">in</span> best[:<span class="dv">3</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>argsort(-sims)</code> sorts descending. Real systems replace this linear scan with an approximate index.</p>
<p><strong>A trainable embedding layer in PyTorch.</strong> Framework code is just the matrix from above.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>embedding <span class="op">=</span> nn.Embedding(num_embeddings<span class="op">=</span><span class="dv">100_000</span>, embedding_dim<span class="op">=</span><span class="dv">768</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>out <span class="op">=</span> embedding(torch.tensor([<span class="dv">3290</span>, <span class="dv">11</span>, <span class="dv">9246</span>]))   <span class="co"># shape (3, 768)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>nn.Embedding</code> stores an <code>E</code> matrix and does the gather; its parameters are learned by the optimiser.</p>
<p><strong>A sentence embedding model.</strong> For search you usually want one vector for a whole sentence.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sentence_transformers <span class="im">import</span> SentenceTransformer</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> SentenceTransformer(<span class="st">"all-MiniLM-L6-v2"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>vectors <span class="op">=</span> model.encode([<span class="st">"a cat sat"</span>, <span class="st">"a dog slept"</span>, <span class="st">"the stock market fell"</span>])</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># shape (3, 384) — one dense vector per sentence</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The three vectors are 384-dimensional. The first two are close; the third is far.</p>
<p><strong>Choosing an embedding model.</strong> The model is a separate decision from the LLM, and it fixes the dimension of your whole index.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Model family</th>
<th>Typical dimension</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>all-MiniLM-L6-v2</code></td>
<td>384</td>
<td>Small, fast, good default for prototypes</td>
</tr>
<tr class="even">
<td><code>all-mpnet-base-v2</code></td>
<td>768</td>
<td>Stronger general-purpose sentence model</td>
</tr>
<tr class="odd">
<td><code>text-embedding-3-small</code></td>
<td>1536</td>
<td>Hosted, cheap, strong baselines</td>
</tr>
<tr class="even">
<td><code>text-embedding-3-large</code></td>
<td>3072</td>
<td>Higher quality, larger index and cost</td>
</tr>
<tr class="odd">
<td>BGE / E5 family</td>
<td>768–1024</td>
<td>Popular open retrieval models</td>
</tr>
<tr class="even">
<td>Cohere <code>embed</code></td>
<td>1024</td>
<td>Hosted, supports compression</td>
</tr>
</tbody>
</table>
<p>Pick one, version it, and store the model name next to the index. Changing it later means re-embedding everything.</p>
<p><strong>Vector search.</strong> A database query returns the nearest stored vectors.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="kw">id</span>, content, embedding <span class="op">&lt;=&gt;</span> <span class="ch">:query_vector</span> <span class="kw">AS</span> distance</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="kw">FROM</span> documents</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="kw">ORDER</span> <span class="kw">BY</span> distance</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="kw">LIMIT</span> <span class="dv">5</span>;</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>&lt;=&gt;</code> is pgvector’s cosine-distance operator. This one query is the retrieval step at the heart of RAG.</p>
</section>
<section id="examples-simple-to-real" class="level2">
<h2 class="anchored" data-anchor-id="examples-simple-to-real">Examples: simple to real</h2>
<p><strong>Example 1 — one-hot vectors are useless for similarity.</strong> Two different one-hot vectors are always orthogonal.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>cat <span class="op">=</span> np.array([<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>dog <span class="op">=</span> np.array([<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>])</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>np.dot(cat, dog)      <span class="co"># 0 — "cat" and "dog" look as unrelated as anything</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>np.dot(cat, cat)      <span class="co"># 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>With one-hot, every distinct pair scores zero. There is no gradient of similarity to exploit.</p>
<p><strong>Example 2 — dot product versus cosine.</strong> Dot product rewards both alignment and length; cosine rewards alignment only.</p>
<pre class="text"><code>a = [1, 2, 3], b = [2, 4, 6]     (b is 2x a)
dot(a, b)  = 28.0     cos(a, b) = 1.0000
a = [1, 2, 3], c = [-1, -2, -3]  (c is -1x a)
dot(a, c)  = -14.0    cos(a, c) = -1.0000
d = [1, 0, 0], e = [0, 1, 0]     (perpendicular)
dot(d, e)  = 0.0      cos = 0.0000</code></pre>
<p>Cosine always lands in <code>[-1, 1]</code>, which makes it easy to threshold: near 1 is similar, near 0 unrelated, near -1 opposite.</p>
<p><strong>Example 3 — semantic neighbourhood.</strong> Given learned vectors, the nearest neighbours of <code>"dog"</code> are the other animals, and far away are vehicles. Using a small hand-made matrix:</p>
<pre class="text"><code>nearest neighbours of 'dog':
  puppy   0.9975
  cat     0.9899
  kitten  0.9754
  car     0.3887
  truck   0.2401</code></pre>
<p>No rules were written. The geometry alone says <code>"dog"</code> is close to <code>"puppy"</code> and far from <code>"truck"</code>. Real embeddings show exactly this pattern.</p>
<p><strong>Example 4 — the parameter cost of an embedding table.</strong> Embeddings are not free; the vocabulary multiplies the dimension.</p>
<pre class="text"><code>vocab=  50,000 dim= 768 -&gt;  38,400,000 floats = 0.077 GB in fp16
vocab= 100,000 dim=1536 -&gt; 153,600,000 floats = 0.307 GB in fp16
vocab= 200,000 dim=4096 -&gt; 819,200,000 floats = 1.638 GB in fp16</code></pre>
<p>A 200k-token vocabulary at 4096 dimensions is over 1.6 GB of parameters before counting the rest of the model. This is why vocabulary size and model size are tuned together.</p>
<p><strong>Example 5 — static versus contextual.</strong> A static embedding gives <code>"bank"</code> one vector forever. A contextual model gives it different vectors depending on the sentence.</p>
<pre class="text"><code>cos(vector("bank"), vector("river"))  = 0.9648   # river-side sense
cos(vector("bank"), vector("money"))  = 0.3032   # financial sense</code></pre>
<p>Same word, different context, different vector. This resolves the classic failure where <code>"river bank"</code> and <code>"savings bank"</code> retrieve each other’s documents. Contextual embedding models are why modern semantic search handles polysemy.</p>
<p><strong>Example 6 — from embeddings to retrieval.</strong> The RAG loop is entirely embedding arithmetic:</p>
<pre class="text"><code>1. embed every document chunk once, store the vectors
2. embed the user question with the same model
3. find the stored vectors nearest the question vector
4. put those chunks in the prompt</code></pre>
<p>Everything hinges on step 2 using the <strong>same</strong> model as step 1. Embeddings from two different models live in different spaces and cannot be compared.</p>
</section>
<section id="in-production" class="level2">
<h2 class="anchored" data-anchor-id="in-production">In production</h2>
<ul>
<li><strong>Never mix embedding models.</strong> A query embedded with model A cannot be searched against an index built with model B. The spaces are unrelated, and the failure is silent — you get plausible but wrong neighbours.</li>
<li><strong>Cosine is the default for text; dot product is faster.</strong> If vectors are normalized to length 1, the two are identical, so many systems normalize once and use dot product.</li>
<li><strong>Dimension is a cost/quality trade.</strong> 384 dimensions is cheap and fast; 1536 or 3072 captures more nuance. Bigger is not always better if your data is small.</li>
<li><strong>Chunking dominates retrieval quality.</strong> A document chopped badly produces an embedding that means nothing. Chunk on natural boundaries and keep some overlap.</li>
<li><strong>Normalize before storing if you use cosine distance.</strong> It avoids recomputing norms and keeps comparisons consistent.</li>
<li><strong>Embedding models have a max input length.</strong> Text beyond it is silently truncated, so a long chunk may be embedded only from its first part.</li>
<li><strong>Static embeddings still exist and are useful.</strong> Word2Vec and GloVe are small and fast; they just cannot disambiguate senses.</li>
<li><strong>Re-embedding is expensive and disruptive.</strong> Changing the model means re-embedding the whole corpus. Version your embedding model with the index.</li>
<li><strong>Beware of anisotropy.</strong> Raw transformer vectors often cluster in a narrow cone, so even unrelated pairs have high cosine similarity. Re-ranking or normalization helps.</li>
<li><strong>Nearest neighbour is not truth.</strong> Similarity finds related text, not correct text. A retrieved chunk can be topically close and factually wrong.</li>
<li><strong>Cache embeddings.</strong> Embedding the same document or query repeatedly is pure waste; cache by content hash.</li>
<li><strong>Evaluate retrieval separately from generation.</strong> If answers are bad, check whether the right chunk was even retrieved before blaming the model.</li>
</ul>
</section>
<section id="interview-questions" class="level2">
<h2 class="anchored" data-anchor-id="interview-questions">Interview questions</h2>
<section id="what-is-an-embedding-and-why-does-a-model-need-one" class="level3">
<h3 class="anchored" data-anchor-id="what-is-an-embedding-and-why-does-a-model-need-one">1. What is an embedding, and why does a model need one?</h3>
<p><strong>Answer.</strong> An embedding is a dense vector of learned numbers that represents a token or text. It replaces an arbitrary ID with a position in a continuous space, so similar items land close together and the model can compute relationships with ordinary math. Without embeddings, token IDs carry no notion of similarity.</p>
<p><strong>Follow-up: “Why not just use one-hot vectors?”</strong> They are huge and every distinct pair is orthogonal, so there is no similarity signal. Embeddings are short and dense, and training shapes the geometry to reflect meaning.</p>
<p><strong>Trap.</strong> Saying embeddings “store the meaning of a word.” They store a learned numerical representation useful for prediction; meaning is an interpretation we place on the geometry.</p>
</section>
<section id="what-is-the-difference-between-dot-product-and-cosine-similarity" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-difference-between-dot-product-and-cosine-similarity">2. What is the difference between dot product and cosine similarity?</h3>
<p><strong>Answer.</strong> The dot product sums the products of matching entries and reflects both direction and magnitude. Cosine similarity divides the dot product by both vector norms, leaving only the angle, and always lies in <code>[-1, 1]</code>. For text, cosine is the usual choice because vector length is often an unhelpful artefact. If vectors are normalized, the two are the same.</p>
<p><strong>Follow-up: “When would dot product be better?”</strong> When magnitude genuinely carries information, or when vectors are pre-normalized for speed. Some models are trained specifically for dot-product scoring.</p>
<p><strong>Trap.</strong> Assuming a high dot product always means high similarity. A long vector can outscore a short one even if it points in a less relevant direction.</p>
</section>
<section id="what-is-the-embedding-matrix-and-how-does-the-lookup-work" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-embedding-matrix-and-how-does-the-lookup-work">3. What is the embedding matrix, and how does the lookup work?</h3>
<p><strong>Answer.</strong> It is a table of shape <code>vocab_size × dimension</code>, with one row per token. A lookup reads the row whose index is the token ID. Multiplying a one-hot vector by the matrix produces the same result, which shows that the embedding layer is a selection, not a real transformation. Backpropagation trains only the rows that appear in the batch.</p>
<p><strong>Follow-up: “How does that interact with the output layer?”</strong> Often the same matrix is reused to score the next token — weight tying. It saves parameters because the output layer needs one vector per vocabulary item anyway.</p>
<p><strong>Trap.</strong> Thinking the embedding layer does matrix multiplication on a dense input. The input is an ID; the operation is a gather.</p>
</section>
<section id="what-is-the-difference-between-static-and-contextual-embeddings" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-difference-between-static-and-contextual-embeddings">4. What is the difference between static and contextual embeddings?</h3>
<p><strong>Answer.</strong> A static embedding gives each word one fixed vector forever, so <code>"bank"</code> is the same vector in every sentence. A contextual embedding is produced by a transformer that mixes in surrounding tokens, so the vector changes with context. Contextual embeddings resolve polysemy and are the basis of modern semantic search.</p>
<p><strong>Follow-up: “Then why does a model even have static embeddings?”</strong> The first layer still needs an initial vector per token. The transformer turns those static inputs into contextual outputs layer by layer.</p>
<p><strong>Trap.</strong> Saying one is strictly better. Static embeddings are small, fast, and often good enough for simple keyword-like similarity.</p>
</section>
<section id="why-do-two-vectors-point-in-similar-directions-if-words-are-related" class="level3">
<h3 class="anchored" data-anchor-id="why-do-two-vectors-point-in-similar-directions-if-words-are-related">5. Why do two vectors point in similar directions if words are related?</h3>
<p><strong>Answer.</strong> Training adjusts the vectors so that they help predict text. Words that appear in similar contexts make similar predictions useful, so their vectors receive similar gradients and drift together. Relatedness is a by-product of the training objective, not a rule anyone wrote.</p>
<p><strong>Follow-up: “Does word order matter?”</strong> Not to a bag-of-words embedding, which loses order. Contextual models encode order through attention and positional information.</p>
<p><strong>Trap.</strong> Believing the famous <code>king - man + woman ≈ queen</code> arithmetic is exact or universal. It is an approximate, dataset-dependent illustration.</p>
</section>
<section id="how-do-embeddings-power-rag-and-vector-search" class="level3">
<h3 class="anchored" data-anchor-id="how-do-embeddings-power-rag-and-vector-search">6. How do embeddings power RAG and vector search?</h3>
<p><strong>Answer.</strong> You embed every document chunk and store the vectors in an index. At query time you embed the question with the same model and ask for the nearest stored vectors — the retrieval step. Those chunks are inserted into the prompt as context. The quality of the answer depends heavily on the quality of this retrieval.</p>
<p><strong>Follow-up: “Why not search by keywords instead?”</strong> Keyword search misses synonyms and paraphrases but is precise for exact identifiers. Production systems often combine both in a hybrid search.</p>
<p><strong>Trap.</strong> Forgetting that query and documents must use the <em>same</em> embedding model. A mismatch returns wrong neighbours without any error.</p>
</section>
<section id="what-does-the-dimension-of-an-embedding-control" class="level3">
<h3 class="anchored" data-anchor-id="what-does-the-dimension-of-an-embedding-control">7. What does the dimension of an embedding control?</h3>
<p><strong>Answer.</strong> Dimension is the amount of space available to encode distinctions. More dimensions can capture finer structure but cost more memory, more compute per comparison, and a larger index. Fewer dimensions are faster and cheaper but blur similar items together.</p>
<p><strong>Follow-up: “How do you choose?”</strong> Start from a strong off-the-shelf model, measure retrieval quality on your own data, and only then consider a smaller or larger dimension. Model quality matters more than dimension alone.</p>
<p><strong>Trap.</strong> Assuming a larger dimension always retrieves better. Without enough training or data, extra dimensions add noise and cost.</p>
</section>
<section id="why-can-an-embedding-model-return-a-high-similarity-for-unrelated-text" class="level3">
<h3 class="anchored" data-anchor-id="why-can-an-embedding-model-return-a-high-similarity-for-unrelated-text">8. Why can an embedding model return a high similarity for unrelated text?</h3>
<p><strong>Answer.</strong> Embeddings are trained for a task, not for truth. Two passages can be topically related yet contradict each other, and the model will still place them close. Some spaces are also anisotropic, so all vectors sit in a narrow cone and even unrelated pairs score high. Normalization, a better model, or a cross-encoder re-ranker usually helps. A <strong>cross-encoder</strong> scores a query and a document together in one pass; that is more accurate than the bi-encoder that produced the vectors but far too slow to run over the whole corpus, so it is used only to re-rank a short candidate list.</p>
<p><strong>Follow-up: “How would you improve retrieval quality?”</strong> Improve chunking, use a model trained for retrieval, normalize, add hybrid keyword search, and re-rank the top candidates with a cross-encoder before sending them to the LLM.</p>
<p><strong>Trap.</strong> Treating cosine similarity as a probability or a measure of correctness. It measures vector alignment, nothing more.</p>
</section>
</section>
<section id="remember-this" class="level2">
<h2 class="anchored" data-anchor-id="remember-this">Remember this</h2>
<ul>
<li>An <strong>embedding</strong> replaces an arbitrary ID with a dense vector, so similar meanings become nearby points.</li>
<li>The <strong>embedding matrix</strong> is <code>vocab_size × dimension</code>; a lookup is a row selection, and training adjusts the rows.</li>
<li><strong>Cosine similarity</strong> compares direction and ignores magnitude; normalize and it equals the dot product.</li>
<li><strong>Static vs contextual</strong>: the first layer is static per token; attention makes the final vectors depend on context.</li>
<li><strong>RAG retrieval is embedding arithmetic</strong>, and query and documents must always use the same embedding model.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ranjeet-h\.github\.io\/agentic-ai-engineer-book");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../phase-02-llm-fundamentals/06-tokenization-and-tokens.html" class="pagination-link" aria-label="Tokenization and Tokens">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Tokenization and Tokens</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../phase-02-llm-fundamentals/08-context-windows-and-kv-cache.html" class="pagination-link" aria-label="Context Windows and the KV Cache">
        <span class="nav-page-text"><span class="chapter-title">Context Windows and the KV Cache</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>