<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Numeric Precision and Quantization – Agentic AI Engineering Study Book</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../phase-02-llm-fundamentals/16-structured-outputs-and-json-schema.html" rel="next">
<link href="../phase-02-llm-fundamentals/14-lora-qlora-peft.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-89355393b13d2c35defd37e977706fc2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-54623c61267def5306c3b17f0a722ca1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../assets/fonts/fonts.css">
<link rel="stylesheet" href="../styles/custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/index.html">Phase 2 — LLM and Generative AI Fundamentals</a></li><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/15-numeric-precision-and-quantization.html"><span class="chapter-title">Numeric Precision and Quantization</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Agentic AI Engineering Study Book</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Study architecture</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-01-production-python/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 — Production Python</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/01-type-hints.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Type Hints</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/02-dataclasses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dataclasses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/03-pydantic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pydantic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/04-decorators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Decorators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/05-iterators-and-generators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Iterators and Generators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/06-context-managers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Managers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/07-exception-handling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Exception Handling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/08-file-handling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">File Handling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/09-async-and-asyncio.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Async and asyncio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/10-threads-and-processes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Threads and Processes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/11-concurrency-patterns.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Concurrency Patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/12-packaging-and-virtual-environments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Packaging and Virtual Environments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/13-dependency-management.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dependency Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/14-logging.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/15-configuration-management.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Configuration Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/16-pytest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">pytest</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/17-mocking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mocking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/18-profiling-and-performance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Profiling and Performance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/19-fastapi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">FastAPI</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/20-sqlalchemy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">SQLAlchemy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/21-alembic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Alembic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/22-postgresql.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">PostgreSQL</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/23-redis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Redis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/24-authentication-and-authorization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Authentication and Authorization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/25-background-jobs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Background Jobs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/26-rate-limiting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Rate Limiting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/27-api-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">API Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/28-dockerizing-python-applications.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dockerizing Python Applications</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/29-cicd-for-python-services.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">CI/CD for Python Services</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-02-llm-fundamentals/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 2 — LLM and Generative AI Fundamentals</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/01-how-ml-and-neural-networks-work.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How Machine Learning and Neural Networks Work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/02-tensors-and-pytorch.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tensors and PyTorch</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/03-forward-pass-and-backpropagation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Forward Pass and Backpropagation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/04-attention-and-self-attention.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Attention and Self-Attention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/05-the-transformer-architecture.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Transformer Architecture</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/06-tokenization-and-tokens.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tokenization and Tokens</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/07-embeddings.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Embeddings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/08-context-windows-and-kv-cache.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Windows and the KV Cache</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/09-logits-softmax-next-token-prediction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logits, Softmax, and Next-Token Prediction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/10-sampling-temperature-top-k-top-p.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sampling: Temperature, Top-K, Top-P</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/11-training-vs-inference-and-batching.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Training vs Inference and Batching</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/12-pretraining-finetuning-instruction-tuning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pretraining, Fine-Tuning, and Instruction Tuning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/13-rlhf-and-preference-alignment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RLHF and Preference Alignment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/14-lora-qlora-peft.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Parameter-Efficient Fine-Tuning: LoRA, QLoRA, PEFT</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/15-numeric-precision-and-quantization.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Numeric Precision and Quantization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/16-structured-outputs-and-json-schema.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Structured Outputs and JSON Schema</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/17-function-and-tool-calling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Function and Tool Calling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/18-streaming-responses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Streaming Responses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/19-prompt-design-and-system-prompts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Prompt Design and System Prompts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/20-context-engineering.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Engineering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/21-hallucinations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hallucinations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/22-prompt-injection-and-context-poisoning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Prompt Injection and Context Poisoning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/23-model-comparison-and-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Model Comparison and Selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/24-provider-apis-openai-anthropic-gemini.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Provider APIs: OpenAI, Anthropic, Gemini</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/25-open-source-models-and-hugging-face.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Open-Source Models and Hugging Face</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-03-rag-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 3 — RAG Engineering</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/01-rag-architecture.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Architecture</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/02-document-ingestion-and-parsing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Document Ingestion and Parsing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/03-chunking-strategies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chunking Strategies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/04-metadata-extraction-and-filtering.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Metadata Extraction and Filtering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/05-embedding-models-and-dimensions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Embedding Models and Dimensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/06-similarity-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Similarity Metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/07-vector-databases-and-ann-indexes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Vector Databases and ANN Indexes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/08-postgresql-pgvector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">PostgreSQL pgvector</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/09-dense-and-sparse-retrieval.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dense and Sparse Retrieval</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/10-hybrid-search.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hybrid Search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/11-query-transformation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Query Transformation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/12-reranking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reranking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/13-context-construction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Construction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/14-citations-and-grounded-generation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Citations and Grounded Generation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/15-knowledge-base-versioning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Knowledge-Base Versioning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/16-rag-caching-and-latency.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Caching and Latency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/17-retrieval-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Retrieval Metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/18-generation-quality-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Generation Quality Metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/19-rag-evaluation-and-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Evaluation and Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/20-multi-tenant-rag.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multi-Tenant RAG</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/21-rag-security-and-access-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Security and Access Control</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#why-this-exists" id="toc-why-this-exists" class="nav-link active" data-scroll-target="#why-this-exists">Why this exists</a></li>
  <li><a href="#start-from-zero" id="toc-start-from-zero" class="nav-link" data-scroll-target="#start-from-zero">Start from zero</a></li>
  <li><a href="#the-core-idea" id="toc-the-core-idea" class="nav-link" data-scroll-target="#the-core-idea">The core idea</a></li>
  <li><a href="#how-it-works" id="toc-how-it-works" class="nav-link" data-scroll-target="#how-it-works">How it works</a></li>
  <li><a href="#the-syntax-you-will-use" id="toc-the-syntax-you-will-use" class="nav-link" data-scroll-target="#the-syntax-you-will-use">The syntax you will use</a></li>
  <li><a href="#examples-simple-to-real" id="toc-examples-simple-to-real" class="nav-link" data-scroll-target="#examples-simple-to-real">Examples: simple to real</a></li>
  <li><a href="#in-production" id="toc-in-production" class="nav-link" data-scroll-target="#in-production">In production</a></li>
  <li><a href="#interview-questions" id="toc-interview-questions" class="nav-link" data-scroll-target="#interview-questions">Interview questions</a></li>
  <li><a href="#remember-this" id="toc-remember-this" class="nav-link" data-scroll-target="#remember-this">Remember this</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/index.html">Phase 2 — LLM and Generative AI Fundamentals</a></li><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/15-numeric-precision-and-quantization.html"><span class="chapter-title">Numeric Precision and Quantization</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Numeric Precision and Quantization</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Interview answer (say this first).</strong> Floating-point formats trade range against precision by splitting bits between an exponent and a mantissa: FP32 and BF16 have a wide exponent, FP16 has a narrow one but more precision. Quantization stores weights in fewer bits, usually INT8 or INT4, by mapping a real range onto a small set of integer levels with a scale. It cuts memory roughly in proportion to the bits, at the cost of some accuracy.</p>
</blockquote>
<section id="why-this-exists" class="level2">
<h2 class="anchored" data-anchor-id="why-this-exists">Why this exists</h2>
<p>Every number in a model takes up space, and a modern model has billions of them. The default format for scientific computing is <strong>FP32</strong> (32-bit floating point), which uses 4 bytes per number. For a 7-billion-parameter model that is 28 GB just for the weights, before any activations or optimizer state. Training needs even more.</p>
<p>The obvious fix is to use fewer bits per number. But floating point is not a fixed number of decimal places. It is closer to scientific notation, and it makes a trade-off:</p>
<ul>
<li>Some values in a neural network are large, and a few are extremely small. If the format’s <strong>range</strong> is too small, small gradients become zero and large activations become infinity.</li>
<li>Training is sensitive to tiny differences. If the format’s <strong>precision</strong> is too low, updates get rounded away and learning stalls.</li>
</ul>
<p>Choosing a format is choosing how to split a fixed budget of bits between range and precision. Get it wrong and training produces <code>NaN</code> or silently stops improving.</p>
<p>Then there is <strong>inference</strong>. Once a model is trained, you usually do not need gradient-level precision to run it. You can store the weights in 8 bits or 4 bits and still get nearly the same answers, which roughly halves or quarters memory. This is <strong>quantization</strong>, and it is why a 70B model can run on hardware that could never hold it in FP32.</p>
<p>Concrete failure: GPUs originally ran FP16 training with no protection, and gradients underflowed to zero, so models stopped learning. The fix was <strong>loss scaling</strong>, which multiplies the loss up before backward and divides it back afterward. BF16 later avoided the problem by keeping FP32’s wide exponent. These are not cosmetic details; they are the reason training works at all.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The one-sentence purpose.</strong> Precision formats decide how many bits describe each number; quantization shrinks those bits to save memory, trading a measurable amount of accuracy for a large drop in cost.</p>
</div>
</div>
</section>
<section id="start-from-zero" class="level2">
<h2 class="anchored" data-anchor-id="start-from-zero">Start from zero</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Word</th>
<th>Plain meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Bit</strong></td>
<td>One binary digit, 0 or 1. Eight bits make a byte.</td>
</tr>
<tr class="even">
<td><strong>Floating point</strong></td>
<td>A way to store real numbers as <code>sign * mantissa * 2^exponent</code>, like scientific notation in base 2.</td>
</tr>
<tr class="odd">
<td><strong>Sign bit</strong></td>
<td>One bit saying positive or negative.</td>
</tr>
<tr class="even">
<td><strong>Exponent</strong></td>
<td>The power of two. It sets <strong>range</strong>: how large and how tiny a number can be.</td>
</tr>
<tr class="odd">
<td><strong>Mantissa</strong> (fraction)</td>
<td>The significant digits. It sets <strong>precision</strong>: how finely values are spaced.</td>
</tr>
<tr class="even">
<td><strong>FP32</strong></td>
<td>32-bit float: 1 sign, 8 exponent, 23 mantissa. The traditional default.</td>
</tr>
<tr class="odd">
<td><strong>FP16</strong></td>
<td>16-bit float: 1 sign, 5 exponent, 10 mantissa. More precision, much less range.</td>
</tr>
<tr class="even">
<td><strong>BF16</strong></td>
<td>16-bit “brain float”: 1 sign, 8 exponent, 7 mantissa. FP32’s range, low precision.</td>
</tr>
<tr class="odd">
<td><strong>Epsilon</strong></td>
<td>The gap between 1.0 and the next representable number. A precision measure.</td>
</tr>
<tr class="even">
<td><strong>Overflow</strong></td>
<td>A number too large to represent, becoming infinity.</td>
</tr>
<tr class="odd">
<td><strong>Underflow</strong></td>
<td>A number too small to represent, becoming zero (or a denormal).</td>
</tr>
<tr class="even">
<td><strong>Denormal</strong></td>
<td>A tiny number below the smallest normal one, with reduced precision.</td>
</tr>
<tr class="odd">
<td><strong>INT8 / INT4</strong></td>
<td>8-bit and 4-bit integers. 256 and 16 distinct levels.</td>
</tr>
<tr class="even">
<td><strong>Quantization</strong></td>
<td>Mapping real numbers onto a small integer grid using a scale (and usually a zero point).</td>
</tr>
<tr class="odd">
<td><strong>Dequantization</strong></td>
<td>Converting the integer back to an approximate real number.</td>
</tr>
<tr class="even">
<td><strong>Scale</strong></td>
<td>The real-world size of one integer step.</td>
</tr>
<tr class="odd">
<td><strong>Zero point</strong></td>
<td>The integer that represents real zero. Needed when the range is not centered.</td>
</tr>
<tr class="even">
<td><strong>Symmetric</strong></td>
<td>Zero maps to zero; the grid is centered. Simple and fast.</td>
</tr>
<tr class="odd">
<td><strong>Asymmetric</strong></td>
<td>The grid is shifted by a zero point so it fits an uneven range exactly.</td>
</tr>
<tr class="even">
<td><strong>Per-tensor</strong></td>
<td>One scale for a whole weight matrix.</td>
</tr>
<tr class="odd">
<td><strong>Per-channel</strong></td>
<td>One scale per row or column. Better accuracy.</td>
</tr>
<tr class="even">
<td><strong>Per-group</strong></td>
<td>One scale per small block of weights, for example 64 or 128 values.</td>
</tr>
<tr class="odd">
<td><strong>Mixed precision</strong></td>
<td>Using more than one format in the same run, for example bf16 compute with fp32 master weights.</td>
</tr>
<tr class="even">
<td><strong>GPTQ / AWQ</strong></td>
<td>Methods that choose quantization scales to minimize output error.</td>
</tr>
<tr class="odd">
<td><strong>GGUF</strong></td>
<td>A file format for quantized models used by <code>llama.cpp</code> on CPUs and Macs.</td>
</tr>
</tbody>
</table>
<p>The key mental split is <strong>range vs precision</strong>. The exponent controls range; the mantissa controls precision. A fixed number of bits cannot maximize both.</p>
</section>
<section id="the-core-idea" class="level2">
<h2 class="anchored" data-anchor-id="the-core-idea">The core idea</h2>
<p>Think of a ruler. A 30-centimetre ruler with millimetre marks measures small things precisely but cannot measure a house. A surveyor’s tape measures a house but not to the millimetre. Same idea: you cannot have both extreme range and extreme precision from the same bits. Floating point spends bits on the exponent to get range and on the mantissa to get precision.</p>
<p>FP32 spends 23 bits on precision. FP16 spends 10, so it is about 8,192 times coarser (2^13) — but it also spends only 5 bits on the exponent, so its largest value is about 65,504, while FP32 reaches about 3.4e38. BF16 keeps 8 exponent bits, so it matches FP32’s range, and pays for it with only 7 mantissa bits.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    A["What are you doing?"] --&gt;|training| B["BF16 compute&lt;br/&gt;+ FP32 master weights"]
    A --&gt;|inference, max quality| C["FP16 or BF16 weights"]
    A --&gt;|inference, save memory| D["Weight-only INT8 / INT4"]
    D --&gt; E["GPU serving&lt;br/&gt;GPTQ / AWQ / bitsandbytes"]
    D --&gt; F["CPU or Mac&lt;br/&gt;GGUF via llama.cpp"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Quantization is a separate idea with its own picture. You have a range of real values, say from -6.4 to 6.4. You pick an integer grid, say -127 to 127. You compute one number, the <strong>scale</strong>, that converts between them. Then each weight is rounded to the nearest grid point:</p>
<pre class="text"><code>scale = max(abs(W)) / 127
q     = round(W / scale)        # store q in 8 bits
W'    = q * scale               # dequantize to use it</code></pre>
<p>The rounded result <code>W'</code> is not exactly <code>W</code>. The difference is <strong>quantization error</strong>, and it is bounded by half a scale step. Everything about quantization is about choosing scales and grid shapes so that this error hurts the model as little as possible.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Format</th>
<th>Bits (s/e/m)</th>
<th>Epsilon at 1.0</th>
<th>Largest value</th>
<th>Bytes per weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FP32</td>
<td>1 / 8 / 23</td>
<td>~1.19e-07</td>
<td>~3.40e+38</td>
<td>4</td>
</tr>
<tr class="even">
<td>FP16</td>
<td>1 / 5 / 10</td>
<td>~9.77e-04</td>
<td>~6.55e+04</td>
<td>2</td>
</tr>
<tr class="odd">
<td>BF16</td>
<td>1 / 8 / 7</td>
<td>~7.81e-03</td>
<td>~3.39e+38</td>
<td>2</td>
</tr>
<tr class="even">
<td>INT8</td>
<td>—</td>
<td>1 of 256 levels</td>
<td>depends on scale</td>
<td>1</td>
</tr>
<tr class="odd">
<td>INT4</td>
<td>—</td>
<td>1 of 16 levels</td>
<td>depends on scale</td>
<td>0.5</td>
</tr>
</tbody>
</table>
</section>
<section id="how-it-works" class="level2">
<h2 class="anchored" data-anchor-id="how-it-works">How it works</h2>
<p><strong>Part 1 — how a floating-point number is stored.</strong></p>
<ol type="1">
<li><strong>Split the bits into three fields.</strong> One sign bit, some exponent bits, and the rest mantissa bits.</li>
<li><strong>The exponent sets range.</strong> It is a power of two applied to the mantissa. More exponent bits means larger and smaller magnitudes are representable.</li>
<li><strong>The mantissa sets precision.</strong> It holds the significant digits after the leading 1. More mantissa bits means finer spacing between nearby numbers.</li>
<li><strong>Precision is relative, not absolute.</strong> The gap between representable numbers grows as the value grows. Near 1.0 in FP32 the gap is about <code>1.19e-07</code>; near 1,000 it is about a thousand times larger. This is why <code>1.0 + 1e-8</code> rounds back to <code>1.0</code> in FP32.</li>
<li><strong>Out-of-range values saturate to infinity.</strong> In FP16, 65,000 is fine and 70,000 becomes <code>inf</code>. Operations involving infinity poison the rest of the computation unless the code checks.</li>
</ol>
<p><strong>Part 2 — how quantization works.</strong></p>
<ol start="6" type="1">
<li><strong>Pick a range.</strong> Usually the observed minimum and maximum of the weights, or a symmetric <code>-max</code> to <code>+max</code>.</li>
<li><strong>Compute the scale.</strong> For symmetric quantization, <code>scale = max(abs(W)) / qmax</code>, where <code>qmax</code> is 127 for signed INT8 or 7 for signed INT4 (the signed 4-bit range is -8..7; 15 is the unsigned 4-bit maximum).</li>
<li><strong>Choose a zero point</strong> for asymmetric quantization: <code>zero = round(qmin - min(W) / scale)</code>. Symmetric needs none, because real zero already maps to integer zero.</li>
<li><strong>Quantize.</strong> <code>q = clip(round(W / scale) + zero, qmin, qmax)</code>. Clip prevents wrap-around if a value falls slightly outside the chosen range.</li>
<li><strong>Dequantize.</strong> <code>W' = (q - zero) * scale</code>. The model uses these approximate values.</li>
<li><strong>Choose the granularity.</strong> One scale per tensor is cheapest and least accurate. One per output channel (row) is common and much better. One per small group of values is better still and is what GPTQ and AWQ use.</li>
<li><strong>Choose the method for the best scales.</strong> GPTQ uses second-order information to pick weights that minimize output error layer by layer. AWQ protects the weights that multiply large activations, because those matter most. GGUF stores a mix of quantization types chosen per layer for CPU inference.</li>
<li><strong>Mixed precision keeps accuracy where it matters.</strong> During training, keep an FP32 master copy of the weights, compute forward and backward in BF16, and update the master copy in FP32. This gets speed and range without losing small updates.</li>
</ol>
</section>
<section id="the-syntax-you-will-use" class="level2">
<h2 class="anchored" data-anchor-id="the-syntax-you-will-use">The syntax you will use</h2>
<p><strong>Inspect a format with NumPy.</strong> <code>np.finfo</code> tells you the exact bits and limits.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>info <span class="op">=</span> np.finfo(np.float16)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>info.bits        <span class="co"># 16</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>info.nmant       <span class="co"># 10 mantissa bits</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>info.nexp        <span class="co"># 5 exponent bits</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>info.eps         <span class="co"># 0.000977  (gap near 1.0)</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>info.tiny        <span class="co"># 6.104e-05 (smallest normal)</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>info.<span class="bu">max</span>         <span class="co"># 6.55e+04  (largest finite)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Move between precisions.</strong> Converting down loses information; converting up cannot restore it.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> np.float32(<span class="fl">1.2345678</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>a.astype(np.float16)      <span class="co"># 1.234  (rounded to fp16 grid)</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>a.astype(np.float32)      <span class="co"># unchanged</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Clip before quantizing.</strong> Real values can exceed the chosen range; clipping stops them wrapping to the opposite sign.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>q <span class="op">=</span> np.clip(np.<span class="bu">round</span>(W <span class="op">/</span> scale), <span class="op">-</span><span class="dv">127</span>, <span class="dv">127</span>).astype(np.int8)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>W_approx <span class="op">=</span> q.astype(np.float32) <span class="op">*</span> scale</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Symmetric quantization, per tensor and per channel.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> quant_symmetric(W):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    s <span class="op">=</span> np.<span class="bu">abs</span>(W).<span class="bu">max</span>() <span class="op">/</span> <span class="fl">127.0</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    q <span class="op">=</span> np.clip(np.<span class="bu">round</span>(W <span class="op">/</span> s), <span class="op">-</span><span class="dv">127</span>, <span class="dv">127</span>).astype(np.int8)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> q, s, q.astype(np.float32) <span class="op">*</span> s</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> quant_per_channel(W, axis<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    s <span class="op">=</span> np.<span class="bu">abs</span>(W).<span class="bu">max</span>(axis<span class="op">=</span>axis, keepdims<span class="op">=</span><span class="va">True</span>) <span class="op">/</span> <span class="fl">127.0</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    q <span class="op">=</span> np.clip(np.<span class="bu">round</span>(W <span class="op">/</span> s), <span class="op">-</span><span class="dv">127</span>, <span class="dv">127</span>).astype(np.int8)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> q, s, q.astype(np.float32) <span class="op">*</span> s</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Asymmetric quantization with a zero point.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>scale <span class="op">=</span> (hi <span class="op">-</span> lo) <span class="op">/</span> (qmax <span class="op">-</span> qmin)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>zero  <span class="op">=</span> <span class="bu">int</span>(<span class="bu">round</span>(qmin <span class="op">-</span> lo <span class="op">/</span> scale))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>q     <span class="op">=</span> np.clip(np.<span class="bu">round</span>(v <span class="op">/</span> scale) <span class="op">+</span> zero, qmin, qmax).astype(np.uint8)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>v_approx <span class="op">=</span> (q.astype(np.float32) <span class="op">-</span> zero) <span class="op">*</span> scale</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Choose a dtype in PyTorch.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> torch.randn(<span class="dv">4</span>, <span class="dv">4</span>, dtype<span class="op">=</span>torch.float32)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>w.to(torch.bfloat16)     <span class="co"># wide range, low precision</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>w.to(torch.float16)      <span class="co"># narrow range, more precision</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Mixed-precision autocast.</strong> PyTorch picks a safe dtype per operation.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.autocast(device_type<span class="op">=</span><span class="st">"cuda"</span>, dtype<span class="op">=</span>torch.bfloat16):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    output <span class="op">=</span> model(input_ids)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> loss_fn(output, labels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Load a 4-bit model with bitsandbytes.</strong> This is the config used for QLoRA; it needs a supported GPU.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> transformers <span class="im">import</span> BitsAndBytesConfig</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>bnb <span class="op">=</span> BitsAndBytesConfig(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    load_in_4bit<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    bnb_4bit_quant_type<span class="op">=</span><span class="st">"nf4"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    bnb_4bit_compute_dtype<span class="op">=</span>torch.bfloat16,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Load an already-quantized model.</strong> GPTQ and AWQ models carry their own config.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> transformers <span class="im">import</span> AutoModelForCausalLM</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>gptq_model <span class="op">=</span> AutoModelForCausalLM.from_pretrained(<span class="st">"model-gptq-4bit"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>awq_model  <span class="op">=</span> AutoModelForCausalLM.from_pretrained(<span class="st">"model-awq-4bit"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="examples-simple-to-real" class="level2">
<h2 class="anchored" data-anchor-id="examples-simple-to-real">Examples: simple to real</h2>
<p><strong>Example 1 — read the actual limits.</strong> These are real values from <code>np.finfo</code>, and they show the trade-off directly.</p>
<pre class="text"><code>float32
  exponent/mantissa bits: 8 / 23
  eps: 1.1920929e-07
  smallest normal: 1.1754944e-38
  largest: 3.4028235e+38
float16
  exponent/mantissa bits: 5 / 10
  eps: 0.000977
  smallest normal: 6.104e-05
  largest: 6.55e+04</code></pre>
<p>FP16 has more precision than the tiny BF16 mantissa but a maximum around 65,504, which is small enough that ordinary neural-network values can overflow.</p>
<p><strong>Example 2 — precision at 1.0.</strong> Adding a small number to 1.0 is the cleanest precision test.</p>
<pre class="text"><code>fp32 1 + 1e-8  = 1.0          # rounded away
fp32 1 + 1e-6  = 1.000001     # kept
fp16 1 + 1e-4  = 1.0          # rounded away
fp16 1 + 5e-3  = 1.005        # kept</code></pre>
<p>This is exactly why tiny gradient updates vanish in low precision unless you keep an FP32 master copy.</p>
<p><strong>Example 3 — range, and the overflow.</strong> FP16 runs out of range where FP32 does not.</p>
<pre class="text"><code>fp16(65000) = 6.5e+04
fp16(70000) = inf            # overflow
fp32(1e30)  = 1e+30
fp16 vs fp32 largest ratio: 5.19e+33</code></pre>
<p>An <code>inf</code> in one layer propagates through the network and produces <code>NaN</code> losses. This is the failure that made FP16 training need loss scaling.</p>
<p><strong>Example 4 — BF16 by construction.</strong> BF16 keeps the sign and 8 exponent bits and drops 16 of the 23 mantissa bits. Frameworks do not simply truncate: they round to nearest even, so a value lands on the closest BF16 grid point.</p>
<pre class="text"><code>fp32 value:    1.2345678
bf16-rounded:  1.234375
to_bf16(1e-4): 1.001358e-04        # round-to-nearest, what torch does
truncated:     9.9658966e-05       # low 16 bits dropped instead (not torch)
bf16 spacing at 1.0 = 2^-7 = 0.0078125</code></pre>
<p>From PyTorch, <code>torch.finfo(torch.bfloat16)</code> gives <code>eps = 0.0078125</code> and <code>max = 3.3895e+38</code> — the same range as FP32, at coarser precision. In BF16, <code>1.0 + 1e-4 = 1.0</code> but <code>1.0 + 0.01 = 1.0078125</code>.</p>
<p><strong>Example 5 — per-tensor vs per-channel error.</strong> Here is a 4x6 weight matrix where one row is large and another is tiny. Per-channel scales fit each row; per-tensor cannot.</p>
<pre class="text"><code>row abs maxes: [6.4042, 1.3040, 2.3250, 0.0683]
per-tensor scale:    0.050427  max abs err: 0.024137
per-channel scales:  [0.050427, 0.010268, 0.018307, 0.000538]
per-channel max err: 0.014792
row-3 error per-tensor:  0.020582
row-3 error per-channel: 0.000178</code></pre>
<p>The small row is quantized about 100x more accurately with per-channel scales, because its own scale is tiny. This is why production quantization is rarely per-tensor.</p>
<p><strong>Example 6 — asymmetric quantization of a shifted range.</strong> When values are all positive, a zero point fits the grid tightly.</p>
<pre class="text"><code>values: [-1.0, 0.0, 0.5, 1.0, 2.0, 4.0]
scale: 0.019608   zero point: 51   (not 0)
codes:      [0, 51, 77, 102, 153, 255]
dequant:    [-1.0, 0.0, 0.5098, 1.0, 2.0, 4.0]
max abs err: 0.009804</code></pre>
<p>The zero point is what lets a <code>uint8</code> grid cover <code>-1.0</code> to <code>4.0</code>. Symmetric quantization would waste half the codes to cover the unused negative side.</p>
<p><strong>Example 7 — memory math for weights.</strong> Memory is parameters times bytes per weight.</p>
<pre class="text"><code>7B weights:  FP32 28.00 GB | FP16/BF16 14.00 GB | INT8 7.00 GB | INT4 3.50 GB</code></pre>
<p>The same arithmetic drives the KV cache, which grows with sequence length. For a 32-layer model with 32 heads, head dimension 128, and 8,192 tokens in FP16:</p>
<pre class="text"><code>2 * 32 layers * 32 heads * 128 * 8192 * 2 bytes = 4,294,967,296 bytes = 4.295 GB</code></pre>
<p>The leading 2 is for keys and values. Halving the cache precision to INT8 would halve this, which is why KV-cache quantization is a common optimization for long contexts.</p>
</section>
<section id="in-production" class="level2">
<h2 class="anchored" data-anchor-id="in-production">In production</h2>
<ul>
<li><strong>Quantize weights, keep activations higher precision first.</strong> Weight-only INT8/INT4 is the safest large win; quantizing activations as well (W8A8) is harder and more accuracy-sensitive.</li>
<li><strong>Prefer per-channel or per-group scales.</strong> Per-tensor is simple and can badly hurt layers with uneven weight ranges. Group sizes of 64 or 128 are standard.</li>
<li><strong>Measure on your own evaluation set.</strong> A model can lose almost nothing on a benchmark and still break on your task. Never ship a quantized model on vibes.</li>
<li><strong>Use BF16 for training, FP16 only with loss scaling.</strong> BF16 matches FP32’s range and is the default on modern accelerators. FP16 has better precision but can underflow, so it relies on scaled loss.</li>
<li><strong>Keep FP32 master weights in mixed precision.</strong> The optimizer update must not be rounded away. This is the whole reason the master copy exists.</li>
<li><strong>Watch for <code>inf</code> and <code>NaN</code> early.</strong> Add a check for non-finite values in the first steps of a run. A single overflow can poison training for hours before anyone notices.</li>
<li><strong>Quantization error is not uniform.</strong> The first and last layers are often kept in higher precision because they are more sensitive. Some pipelines exclude them from quantization.</li>
<li><strong>GPTQ, AWQ, and GGUF are not interchangeable.</strong> GPTQ and AWQ target GPU serving with different error-minimization strategies; GGUF targets CPU and Apple silicon with a family of mixed formats such as <code>Q4_K_M</code>. Match the format to the runtime.</li>
<li><strong>4-bit is usually the practical floor for weights.</strong> Below that, quality degrades quickly on hard tasks. 3-bit and 2-bit methods exist but need careful evaluation.</li>
<li><strong>Memory is not the only win.</strong> Quantized inference is often faster because it is memory-bandwidth bound: moving fewer bytes per weight speeds up the layer even when the maths is the same.</li>
<li><strong>Check the hardware support.</strong> Some accelerators have fast INT8 and no fast INT4, so an INT4 model can be slower despite using less memory.</li>
<li><strong>Calibration data matters.</strong> Post-training quantization uses sample inputs to choose scales. Poor or unrepresentative calibration data quietly biases every scale.</li>
</ul>
</section>
<section id="interview-questions" class="level2">
<h2 class="anchored" data-anchor-id="interview-questions">Interview questions</h2>
<section id="what-is-the-difference-between-fp32-fp16-and-bf16" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-difference-between-fp32-fp16-and-bf16">1. What is the difference between FP32, FP16, and BF16?</h3>
<p><strong>Answer.</strong> All three are floating-point formats, but they split their bits differently. FP32 uses 8 exponent and 23 mantissa bits. FP16 uses 5 exponent and 10 mantissa bits, so it has a small range (max about 65,504) but decent precision. BF16 uses 8 exponent and 7 mantissa bits, so it matches FP32’s range but has much coarser precision. BF16 is the default for training because range matters for gradients and it needs no loss scaling.</p>
<p><strong>Follow-up: “Why not always use FP16, since it is more precise?”</strong> Its narrow range causes overflow and underflow, so FP16 training needs loss scaling. BF16 avoids that at the cost of precision, which training tolerates.</p>
<p><strong>Trap.</strong> Saying BF16 is “just FP32 with fewer bits”. It keeps FP32’s exponent but loses most of the mantissa, so the precision is much lower than FP32.</p>
</section>
<section id="what-do-the-exponent-and-mantissa-control" class="level3">
<h3 class="anchored" data-anchor-id="what-do-the-exponent-and-mantissa-control">2. What do the exponent and mantissa control?</h3>
<p><strong>Answer.</strong> The exponent sets range: it is the power of two, so more exponent bits allow larger and smaller magnitudes. The mantissa sets precision: it holds the significant digits, so more mantissa bits mean representable numbers are closer together. Because the precision is relative, the absolute gap grows with the magnitude of the value.</p>
<p><strong>Follow-up: “Why is <code>1.0 + 1e-8</code> equal to <code>1.0</code> in FP32?”</strong> Because FP32’s epsilon near 1.0 is about <code>1.19e-07</code>, which is larger than <code>1e-8</code>. The true result lies between representable numbers and rounds back to 1.0.</p>
<p><strong>Trap.</strong> Thinking precision is a fixed number of decimal places. Floating point has significant digits, so precision scales with magnitude.</p>
</section>
<section id="what-is-quantization-and-how-does-it-save-memory" class="level3">
<h3 class="anchored" data-anchor-id="what-is-quantization-and-how-does-it-save-memory">3. What is quantization, and how does it save memory?</h3>
<p><strong>Answer.</strong> Quantization maps real weights onto a small integer grid using a scale and often a zero point. Storing 8-bit or 4-bit integers instead of 16-bit floats cuts memory by 2x or 4x. The model dequantizes on the fly to compute in a higher-precision format. It saves memory because each weight needs fewer bits; it can also speed up bandwidth-bound inference.</p>
<p><strong>Follow-up: “Where does the accuracy loss come from?”</strong> Rounding to the grid introduces error bounded by half a scale step. The error is larger where the scale is large, so scale choice and granularity determine quality.</p>
<p><strong>Trap.</strong> Claiming quantization is lossless. It is a compression with measurable error; stating the trade-off is part of a good answer.</p>
</section>
<section id="symmetric-vs-asymmetric-quantization-what-is-the-difference" class="level3">
<h3 class="anchored" data-anchor-id="symmetric-vs-asymmetric-quantization-what-is-the-difference">4. Symmetric vs asymmetric quantization — what is the difference?</h3>
<p><strong>Answer.</strong> Symmetric quantization centers the grid on zero, so real zero maps to integer zero and no zero point is stored. It is simple and fast. Asymmetric quantization adds a zero point that shifts the grid to fit an uneven range, such as an all-positive distribution, using all available levels. It is more accurate for skewed ranges but costs a little extra computation.</p>
<p><strong>Follow-up: “When does symmetric waste levels?”</strong> When the data range is not centered on zero, for example all-positive values. Half the grid covers values that never occur, so those levels are wasted and the effective step is larger.</p>
<p><strong>Trap.</strong> Assuming asymmetric is always better. It is better for skewed ranges but adds a zero point and is slightly more complex, and symmetric often wins in hardware that has specialized support for it.</p>
</section>
<section id="per-tensor-vs-per-channel-vs-per-group-quantization" class="level3">
<h3 class="anchored" data-anchor-id="per-tensor-vs-per-channel-vs-per-group-quantization">5. Per-tensor vs per-channel vs per-group quantization?</h3>
<p><strong>Answer.</strong> Per-tensor uses one scale for a whole matrix, per-channel uses one scale per output channel (row or column), and per-group uses one scale per small block of weights, commonly 64 or 128 values. Finer granularity means scales fit local ranges better, so accuracy improves, at the cost of storing and applying more scales.</p>
<p><strong>Follow-up: “How much difference can granularity make?”</strong> In a measured 4x6 example where one row had max 6.40 and another had max 0.068, the largest error on the small row was 0.020582 per-tensor versus 0.000178 per-channel — about two orders of magnitude better.</p>
<p><strong>Trap.</strong> Believing one scale per tensor is enough. Real weight matrices have rows with very different magnitudes, and a single scale is set by the largest one, punishing the smallest.</p>
</section>
<section id="what-are-gptq-awq-and-gguf" class="level3">
<h3 class="anchored" data-anchor-id="what-are-gptq-awq-and-gguf">6. What are GPTQ, AWQ, and GGUF?</h3>
<p><strong>Answer.</strong> They are quantization approaches and formats for inference. GPTQ quantizes layer by layer and uses second-order information to pick weights that minimize output error. AWQ is activation-aware: it protects the weight channels that multiply the largest activations, because those matter most. GGUF is a file format from <code>llama.cpp</code> that stores weights at mixed quantization types for CPU and Apple-silicon inference.</p>
<p><strong>Follow-up: “Which should I pick?”</strong> It depends on the runtime. GPU serving usually picks GPTQ or AWQ; CPU and Mac inference usually picks GGUF. The best choice for your accuracy target is the one you measured.</p>
<p><strong>Trap.</strong> Treating them as equivalent. They differ in what they optimize, and their quality at the same bit width can differ on your task.</p>
</section>
<section id="what-is-mixed-precision-training-and-why-keep-fp32-master-weights" class="level3">
<h3 class="anchored" data-anchor-id="what-is-mixed-precision-training-and-why-keep-fp32-master-weights">7. What is mixed-precision training, and why keep FP32 master weights?</h3>
<p><strong>Answer.</strong> Mixed precision computes forward and backward passes in BF16 or FP16 for speed, while keeping an FP32 master copy of the weights. The optimizer updates the master weights in FP32, so tiny updates are not rounded away, then casts them to the compute format for the next step. It gives most of the speed benefit with stable training.</p>
<p><strong>Follow-up: “Why does FP16 need loss scaling and BF16 not?”</strong> FP16’s small exponent makes small gradients underflow to zero, so the loss is scaled up before backward and scaled back after. BF16 has FP32’s exponent range, so gradients stay representable and scaling is unnecessary.</p>
<p><strong>Trap.</strong> Thinking mixed precision only saves memory. Its main benefit is speed from faster low-precision matrix maths, and the memory saving is secondary.</p>
</section>
<section id="how-does-quantization-interact-with-kv-cache-and-context-length" class="level3">
<h3 class="anchored" data-anchor-id="how-does-quantization-interact-with-kv-cache-and-context-length">8. How does quantization interact with KV cache and context length?</h3>
<p><strong>Answer.</strong> The KV cache stores the keys and values for every past token, so it grows linearly with context length and can rival the weights. Quantizing the cache to INT8 or lower halves or quarters that memory, which directly extends the usable context. The arithmetic is the same as for weights: bytes equal values times bytes per value, and a 32-layer, 32-head, head-dimension-128 model at 8,192 tokens needs about 4.3 GB at FP16.</p>
<p><strong>Follow-up: “Is cache quantization safe?”</strong> It is usually more sensitive than weight-only quantization because attention scores depend on fine differences in keys. Test it; many systems keep the cache at FP16 and quantize only the weights.</p>
<p><strong>Trap.</strong> Forgetting the cache when estimating memory. On long-context serving the KV cache is often the bottleneck, not the weights.</p>
</section>
</section>
<section id="remember-this" class="level2">
<h2 class="anchored" data-anchor-id="remember-this">Remember this</h2>
<ul>
<li><strong>Exponent sets range, mantissa sets precision.</strong> A fixed bit budget cannot maximize both.</li>
<li><strong>FP16 has more precision and less range; BF16 has FP32’s range and less precision.</strong> BF16 is the training default.</li>
<li><strong>Quantization maps values onto an integer grid with a scale</strong>, plus a zero point when the range is not centered.</li>
<li><strong>Finer granularity means better accuracy</strong>: per-channel or per-group beats per-tensor.</li>
<li><strong>INT8 and INT4 cut memory 2x and 4x.</strong> Measure quality yourself; do not assume it is free.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ranjeet-h\.github\.io\/agentic-ai-engineer-book");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../phase-02-llm-fundamentals/14-lora-qlora-peft.html" class="pagination-link" aria-label="Parameter-Efficient Fine-Tuning: LoRA, QLoRA, PEFT">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Parameter-Efficient Fine-Tuning: LoRA, QLoRA, PEFT</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../phase-02-llm-fundamentals/16-structured-outputs-and-json-schema.html" class="pagination-link" aria-label="Structured Outputs and JSON Schema">
        <span class="nav-page-text"><span class="chapter-title">Structured Outputs and JSON Schema</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>