<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Streaming Responses – Agentic AI Engineering Study Book</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../phase-02-llm-fundamentals/19-prompt-design-and-system-prompts.html" rel="next">
<link href="../phase-02-llm-fundamentals/17-function-and-tool-calling.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-89355393b13d2c35defd37e977706fc2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-54623c61267def5306c3b17f0a722ca1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../assets/fonts/fonts.css">
<link rel="stylesheet" href="../styles/custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/index.html">Phase 2 — LLM and Generative AI Fundamentals</a></li><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/18-streaming-responses.html"><span class="chapter-title">Streaming Responses</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Agentic AI Engineering Study Book</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Study architecture</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-01-production-python/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 — Production Python</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/01-type-hints.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Type Hints</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/02-dataclasses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dataclasses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/03-pydantic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pydantic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/04-decorators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Decorators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/05-iterators-and-generators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Iterators and Generators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/06-context-managers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Managers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/07-exception-handling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Exception Handling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/08-file-handling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">File Handling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/09-async-and-asyncio.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Async and asyncio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/10-threads-and-processes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Threads and Processes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/11-concurrency-patterns.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Concurrency Patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/12-packaging-and-virtual-environments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Packaging and Virtual Environments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/13-dependency-management.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dependency Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/14-logging.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/15-configuration-management.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Configuration Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/16-pytest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">pytest</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/17-mocking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mocking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/18-profiling-and-performance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Profiling and Performance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/19-fastapi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">FastAPI</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/20-sqlalchemy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">SQLAlchemy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/21-alembic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Alembic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/22-postgresql.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">PostgreSQL</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/23-redis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Redis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/24-authentication-and-authorization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Authentication and Authorization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/25-background-jobs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Background Jobs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/26-rate-limiting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Rate Limiting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/27-api-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">API Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/28-dockerizing-python-applications.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dockerizing Python Applications</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/29-cicd-for-python-services.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">CI/CD for Python Services</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-02-llm-fundamentals/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 2 — LLM and Generative AI Fundamentals</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/01-how-ml-and-neural-networks-work.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How Machine Learning and Neural Networks Work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/02-tensors-and-pytorch.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tensors and PyTorch</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/03-forward-pass-and-backpropagation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Forward Pass and Backpropagation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/04-attention-and-self-attention.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Attention and Self-Attention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/05-the-transformer-architecture.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Transformer Architecture</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/06-tokenization-and-tokens.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tokenization and Tokens</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/07-embeddings.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Embeddings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/08-context-windows-and-kv-cache.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Windows and the KV Cache</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/09-logits-softmax-next-token-prediction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logits, Softmax, and Next-Token Prediction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/10-sampling-temperature-top-k-top-p.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sampling: Temperature, Top-K, Top-P</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/11-training-vs-inference-and-batching.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Training vs Inference and Batching</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/12-pretraining-finetuning-instruction-tuning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pretraining, Fine-Tuning, and Instruction Tuning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/13-rlhf-and-preference-alignment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RLHF and Preference Alignment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/14-lora-qlora-peft.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Parameter-Efficient Fine-Tuning: LoRA, QLoRA, PEFT</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/15-numeric-precision-and-quantization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Numeric Precision and Quantization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/16-structured-outputs-and-json-schema.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Structured Outputs and JSON Schema</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/17-function-and-tool-calling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Function and Tool Calling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/18-streaming-responses.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Streaming Responses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/19-prompt-design-and-system-prompts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Prompt Design and System Prompts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/20-context-engineering.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Engineering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/21-hallucinations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hallucinations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/22-prompt-injection-and-context-poisoning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Prompt Injection and Context Poisoning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/23-model-comparison-and-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Model Comparison and Selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/24-provider-apis-openai-anthropic-gemini.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Provider APIs: OpenAI, Anthropic, Gemini</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/25-open-source-models-and-hugging-face.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Open-Source Models and Hugging Face</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#why-this-exists" id="toc-why-this-exists" class="nav-link active" data-scroll-target="#why-this-exists">Why this exists</a></li>
  <li><a href="#start-from-zero" id="toc-start-from-zero" class="nav-link" data-scroll-target="#start-from-zero">Start from zero</a></li>
  <li><a href="#the-core-idea" id="toc-the-core-idea" class="nav-link" data-scroll-target="#the-core-idea">The core idea</a></li>
  <li><a href="#how-it-works" id="toc-how-it-works" class="nav-link" data-scroll-target="#how-it-works">How it works</a></li>
  <li><a href="#the-syntax-you-will-use" id="toc-the-syntax-you-will-use" class="nav-link" data-scroll-target="#the-syntax-you-will-use">The syntax you will use</a></li>
  <li><a href="#examples-simple-to-real" id="toc-examples-simple-to-real" class="nav-link" data-scroll-target="#examples-simple-to-real">Examples: simple to real</a></li>
  <li><a href="#in-production" id="toc-in-production" class="nav-link" data-scroll-target="#in-production">In production</a></li>
  <li><a href="#interview-questions" id="toc-interview-questions" class="nav-link" data-scroll-target="#interview-questions">Interview questions</a></li>
  <li><a href="#remember-this" id="toc-remember-this" class="nav-link" data-scroll-target="#remember-this">Remember this</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/index.html">Phase 2 — LLM and Generative AI Fundamentals</a></li><li class="breadcrumb-item"><a href="../phase-02-llm-fundamentals/18-streaming-responses.html"><span class="chapter-title">Streaming Responses</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Streaming Responses</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Interview answer (say this first).</strong> Streaming sends each token to the client as the model produces it, instead of waiting for the whole answer. It does not make generation faster, but it cuts <strong>time-to-first-token</strong> from seconds to a fraction of a second, and that is what users perceive as speed. Providers deliver the tokens as server-sent events, and the client reassembles the deltas into the final text.</p>
</blockquote>
<section id="why-this-exists" class="level2">
<h2 class="anchored" data-anchor-id="why-this-exists">Why this exists</h2>
<p>A language model produces one token at a time. A 300-token answer generated at 40 tokens per second takes about <strong>7.5 seconds</strong> of work. The question is what the user sees during those 7.5 seconds.</p>
<p>Without streaming, the client sends a request and waits for the entire response. The screen stays empty until the last token is generated:</p>
<pre class="text"><code>0s ───────────────────────────────────────────── 7.5s
[                    empty screen                 ][ whole answer appears ]</code></pre>
<p>Users do not read “7.5 seconds”. They read <strong>nothing is happening</strong>, so they click again (starting a second expensive request), close the tab (throwing away paid-for tokens), or blame the model for a normal generation time.</p>
<p>Now compare streaming:</p>
<pre class="text"><code>0s ─────── 0.4s ─────────────────────────────── 7.5s
[ wait ]  [ first token ][ more tokens arrive ][ done ]</code></pre>
<p>The total work is identical. Generation is not faster. But the first visible result arrives in about <strong>0.4 seconds</strong> instead of 7.5 seconds — roughly <strong>19 times sooner to first content</strong>. That is the entire value: streaming changes <em>perceived</em> latency, not actual latency.</p>
<p>Streaming also matters beyond chat. An agent that reasons for twenty seconds and then calls a tool can stream its intermediate “thinking” text so the user sees progress. A coding assistant can show code appearing line by line. A voice assistant needs the first words as early as possible so speech can begin.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The one-sentence purpose.</strong> Streaming turns one long wait into many short waits, so the user sees the answer forming instead of staring at a blank screen.</p>
</div>
</div>
</section>
<section id="start-from-zero" class="level2">
<h2 class="anchored" data-anchor-id="start-from-zero">Start from zero</h2>
<p>Every term below is used for the rest of the page. Pin them down now.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Word</th>
<th>Plain meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Token</strong></td>
<td>The unit of text a model produces — roughly a word piece, often 3–4 characters of English.</td>
</tr>
<tr class="even">
<td><strong>Latency</strong></td>
<td>How long something takes, measured in milliseconds (ms) or seconds.</td>
</tr>
<tr class="odd">
<td><strong>Time-to-first-token (TTFT)</strong></td>
<td>The delay between sending the request and receiving the first token.</td>
</tr>
<tr class="even">
<td><strong>Inter-token latency</strong></td>
<td>The average delay between one token and the next.</td>
</tr>
<tr class="odd">
<td><strong>Total latency</strong></td>
<td>The full time from request to the last token.</td>
</tr>
<tr class="even">
<td><strong>Perceived latency</strong></td>
<td>How slow the system <em>feels</em> to a user. Driven mostly by TTFT, not total time.</td>
</tr>
<tr class="odd">
<td><strong>Streaming</strong></td>
<td>Sending each piece of the answer as soon as it is ready, over a connection that stays open.</td>
</tr>
<tr class="even">
<td><strong>Server-sent events (SSE)</strong></td>
<td>A simple text protocol for a server to push a stream of events to a client.</td>
</tr>
<tr class="odd">
<td><strong>Chunk</strong></td>
<td>One message in the stream. It usually carries a small piece of the answer.</td>
</tr>
<tr class="even">
<td><strong>Delta</strong></td>
<td>The <em>change</em> in that chunk — the new text, not the whole text so far.</td>
</tr>
<tr class="odd">
<td><strong><code>finish_reason</code></strong></td>
<td>A field that says why generation stopped: <code>stop</code>, <code>length</code>, <code>tool_calls</code>, or <code>content_filter</code>.</td>
</tr>
<tr class="even">
<td><strong>Buffering</strong></td>
<td>Holding data back before passing it on. A proxy that buffers destroys streaming.</td>
</tr>
<tr class="odd">
<td><strong>Cancellation</strong></td>
<td>Closing the connection to stop generation early, usually to save cost.</td>
</tr>
</tbody>
</table>
<p>Two pairs cause most of the confusion: <strong>TTFT vs total latency</strong> (streaming improves the wait before anything appears, not the time to finish) and <strong>chunk vs delta</strong> (a chunk is the envelope; the delta is the new text inside it, which you append).</p>
</section>
<section id="the-core-idea" class="level2">
<h2 class="anchored" data-anchor-id="the-core-idea">The core idea</h2>
<p>Picture a restaurant. The kitchen cooks six dishes one after another.</p>
<ul>
<li><strong>Non-streaming service:</strong> the waiter waits until all six dishes are cooked, then brings them at once. The customer sits hungry for the full cooking time.</li>
<li><strong>Streaming service:</strong> the waiter brings each dish the moment it leaves the pan. The last dish still arrives at the same time, but the customer starts eating immediately.</li>
</ul>
<p>The waiter is the streaming connection. The dishes are tokens. Nothing in the kitchen got faster; the <em>experience</em> changed.</p>
<p>Here is the flow over time:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">sequenceDiagram
    participant U as User
    participant C as Client
    participant S as Model server
    U-&gt;&gt;C: "Summarise this report"
    C-&gt;&gt;S: POST with stream=true
    Note over S: prefill: read the whole prompt,&lt;br/&gt;this delay is the TTFT
    S--&gt;&gt;C: chunk 1 (delta "The")
    S--&gt;&gt;C: chunk 2 (delta " report")
    S--&gt;&gt;C: chunk 3 (delta " covers")
    Note over C: append each delta,&lt;br/&gt;re-render the text
    S--&gt;&gt;C: data: [DONE]
    C--&gt;&gt;U: final answer visible, token by token
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>The two modes differ in more than latency, and the differences are exactly what interviewers probe:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Non-streaming</th>
<th>Streaming</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Time until first visible text</td>
<td>Total latency (seconds)</td>
<td>TTFT (fraction of a second)</td>
</tr>
<tr class="even">
<td>Total generation time</td>
<td>Same</td>
<td>Same, plus tiny per-chunk overhead</td>
</tr>
<tr class="odd">
<td>Connection lifetime</td>
<td>One short request/response</td>
<td>Held open for the whole answer</td>
</tr>
<tr class="even">
<td>Detecting failure</td>
<td>One error response, or none</td>
<td>Error may arrive after partial text</td>
</tr>
<tr class="odd">
<td>Structured output</td>
<td>Parse one complete JSON string</td>
<td>Must parse incomplete JSON while it grows</td>
</tr>
<tr class="even">
<td>Tool calls</td>
<td>One complete arguments string</td>
<td>Arguments arrive as string fragments to join</td>
</tr>
</tbody>
</table>
<p>If you remember one line from this page, remember the table row about perceived latency: <strong>users feel TTFT, not total latency.</strong></p>
</section>
<section id="how-it-works" class="level2">
<h2 class="anchored" data-anchor-id="how-it-works">How it works</h2>
<ol type="1">
<li><strong>The client asks for a stream.</strong> It sends the normal request with <code>stream=true</code> (or the provider’s equivalent). The server no longer promises a single complete body.</li>
<li><strong>The server processes the prompt.</strong> It reads the system message, the history, and the tool schemas. This step is called <strong>prefill</strong>, and for a long prompt it is most of the TTFT. The model then emits the first token, which the server writes out immediately.</li>
<li><strong>The connection stays open.</strong> Instead of closing after one response, the server keeps sending bytes. Over HTTP/1.1 this uses chunked transfer encoding; the body has no fixed length.</li>
<li><strong>Each token is wrapped as an event.</strong> The provider formats each piece as server-sent events. A raw event looks like <code>data: {...}\n\n</code>. A blank line ends one event; the next line begins the next.</li>
<li><strong>The client reads, parses, and appends.</strong> As bytes arrive, it splits them into events, parses each JSON payload, extracts the delta — the object such as <code>{"delta": {"content": " covers"}}</code> — and adds it to a growing string. This is the step that makes text appear.</li>
<li><strong>Tool-call arguments are accumulated.</strong> When the model calls a tool, the arguments are not sent whole. Each chunk carries a fragment like <code>'{"ci'</code> then <code>'ty": "Pune"}'</code>. The client concatenates the fragments and only then parses the JSON.</li>
<li><strong>The stream ends.</strong> The provider sends a final chunk with a <code>finish_reason</code>, then a sentinel such as <code>data: [DONE]</code>. The client stops reading and closes the connection.</li>
<li><strong>Failure or cancellation can happen at any point.</strong> If the connection drops at token 40, the client keeps the 40 tokens it has and decides whether to retry, resume, or show an error.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Why SSE and not websockets?</strong> Streaming is one-directional: the server sends, the client mostly listens. SSE is exactly that shape, rides on ordinary HTTP, and needs no special protocol upgrade. Websockets are for two-way, low-latency traffic, which is more machinery than one-way token output needs.</p>
</div>
</div>
</section>
<section id="the-syntax-you-will-use" class="level2">
<h2 class="anchored" data-anchor-id="the-syntax-you-will-use">The syntax you will use</h2>
<p>These are the real forms, smallest to largest.</p>
<p><strong>OpenAI, synchronous streaming.</strong> The API returns an iterator of chunks instead of one completion.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> openai <span class="im">import</span> OpenAI</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>client <span class="op">=</span> OpenAI()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>stream <span class="op">=</span> client.chat.completions.create(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    model<span class="op">=</span><span class="st">"gpt-4o-mini"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    messages<span class="op">=</span>[{<span class="st">"role"</span>: <span class="st">"user"</span>, <span class="st">"content"</span>: <span class="st">"Explain tokens briefly."</span>}],</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    stream<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> chunk <span class="kw">in</span> stream:</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> chunk.choices:          <span class="co"># usage-only chunk: choices == [], so skip it</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">continue</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    piece <span class="op">=</span> chunk.choices[<span class="dv">0</span>].delta.content <span class="kw">or</span> <span class="st">""</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(piece, end<span class="op">=</span><span class="st">""</span>, flush<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The <code>chunk.choices[0].delta</code> field holds the new piece. <code>content</code> can be <code>None</code> on control chunks, so <code>or ""</code> protects you. <code>choices</code> can also be <strong>empty</strong>, which happens on the final usage-only chunk when <code>stream_options={"include_usage": True}</code> is set — guard with <code>if not chunk.choices: continue</code> before indexing, or that chunk raises <code>IndexError</code>. The async SDK (<code>AsyncOpenAI</code>) has the same shape: <code>await client.chat.completions.create(..., stream=True)</code>, then <code>async for chunk in stream</code>.</p>
<p><strong>Reading the finish reason.</strong> The final chunk carries why generation stopped; its delta is empty and only <code>finish_reason</code> is set.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> chunk.choices <span class="kw">and</span> chunk.choices[<span class="dv">0</span>].finish_reason:</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(chunk.choices[<span class="dv">0</span>].finish_reason)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># "stop" | "length" | "tool_calls" | "content_filter"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>"length"</code> means the answer hit your token limit and was cut off — a real production bug if you never check it.</p>
<p><strong>Real token usage while streaming.</strong> Add <code>stream_options</code> to get a final chunk carrying usage. That chunk has <code>choices == []</code>, so the loop must skip it before reading a delta.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>stream <span class="op">=</span> client.chat.completions.create(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    model<span class="op">=</span><span class="st">"gpt-4o-mini"</span>, messages<span class="op">=</span>[{<span class="st">"role"</span>: <span class="st">"user"</span>, <span class="st">"content"</span>: <span class="st">"Hi"</span>}],</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    stream<span class="op">=</span><span class="va">True</span>, stream_options<span class="op">=</span>{<span class="st">"include_usage"</span>: <span class="va">True</span>},</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>usage <span class="op">=</span> <span class="va">None</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> chunk <span class="kw">in</span> stream:</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> chunk.choices:          <span class="co"># final usage-only chunk: choices == []</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        usage <span class="op">=</span> chunk.usage</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">continue</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(chunk.choices[<span class="dv">0</span>].delta.content <span class="kw">or</span> <span class="st">""</span>, end<span class="op">=</span><span class="st">""</span>, flush<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(usage)                       <span class="co"># CompletionUsage(prompt_tokens=..., ...)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Without this, streamed calls do not report token usage in the response body; you have to estimate or ask for it.</p>
<p><strong>Anthropic, streaming with a helper.</strong> The helper gives you a clean iterator of text strings.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> anthropic <span class="im">import</span> Anthropic</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>client <span class="op">=</span> Anthropic()</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> client.messages.stream(</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    model<span class="op">=</span><span class="st">"claude-sonnet-4-5"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    max_tokens<span class="op">=</span><span class="dv">1024</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    messages<span class="op">=</span>[{<span class="st">"role"</span>: <span class="st">"user"</span>, <span class="st">"content"</span>: <span class="st">"Explain streaming."</span>}],</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>) <span class="im">as</span> stream:</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> text <span class="kw">in</span> stream.text_stream:</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(text, end<span class="op">=</span><span class="st">""</span>, flush<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    final <span class="op">=</span> stream.get_final_message()   <span class="co"># the assembled message</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>text_stream</code> yields text pieces. <code>get_final_message()</code> returns the complete message once the stream ends, which is convenient for logging. The async version uses <code>AsyncAnthropic</code> with <code>async with</code> and <code>async for</code> in exactly the same shape.</p>
<p><strong>The raw SSE wire format.</strong> This is what travels over the socket, regardless of provider.</p>
<pre class="text"><code>event: content_block_delta
data: {"type":"content_block_delta","delta":{"type":"text_delta","text":"Hello"}}

data: {"choices":[{"delta":{"content":" world"}}]}

data: [DONE]</code></pre>
<p>A blank line separates events. Lines starting with <code>:</code> are comments. <code>[DONE]</code> is an OpenAI convention, not part of the SSE standard.</p>
<p><strong>Parsing SSE yourself.</strong> This is the loop every SDK hides.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> parse_sse(lines):</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> line <span class="kw">in</span> lines:</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>        line <span class="op">=</span> line.rstrip(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="kw">not</span> line <span class="kw">or</span> line.startswith(<span class="st">":"</span>):</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span>                      <span class="co"># blank separator or keep-alive comment</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> line.startswith(<span class="st">"data:"</span>):</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>            payload <span class="op">=</span> line[<span class="bu">len</span>(<span class="st">"data:"</span>):].strip()</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> payload <span class="op">==</span> <span class="st">"[DONE]"</span>:</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>                <span class="cf">return</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>            <span class="cf">yield</span> json.loads(payload)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Cancelling a stream.</strong> Calling <code>stream.close()</code> (or exiting the client’s context manager) stops reading and releases the connection, so you stop paying for tokens you no longer need. Closing is the signal to stop; a few tokens may already be in flight, so it is fast but not instantaneous.</p>
</section>
<section id="examples-simple-to-real" class="level2">
<h2 class="anchored" data-anchor-id="examples-simple-to-real">Examples: simple to real</h2>
<p><strong>Example 1 — simulate a token stream and measure it.</strong> Real providers are not needed to see the shape. This async generator waits once for the first token, then a little between tokens.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> asyncio, time</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="cf">async</span> <span class="kw">def</span> stream_tokens(prompt, tokens, ttft<span class="op">=</span><span class="fl">0.30</span>, per_token<span class="op">=</span><span class="fl">0.08</span>):</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">await</span> asyncio.sleep(ttft)          <span class="co"># queue + prefill: time to first token</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> tok <span class="kw">in</span> tokens:</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">yield</span> {<span class="st">"delta"</span>: tok}</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">await</span> asyncio.sleep(per_token) <span class="co"># inter-token latency</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="cf">async</span> <span class="kw">def</span> consume(prompt, tokens):</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    start <span class="op">=</span> time.perf_counter()</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    first_at <span class="op">=</span> <span class="va">None</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    pieces <span class="op">=</span> []</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">async</span> <span class="cf">for</span> chunk <span class="kw">in</span> stream_tokens(prompt, tokens):</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> first_at <span class="kw">is</span> <span class="va">None</span>:</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>            first_at <span class="op">=</span> time.perf_counter()   <span class="co"># TTFT is measured here</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>        pieces.append(chunk[<span class="st">"delta"</span>])</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    end <span class="op">=</span> time.perf_counter()</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">""</span>.join(pieces), (first_at <span class="op">-</span> start) <span class="op">*</span> <span class="dv">1000</span>, (end <span class="op">-</span> start) <span class="op">*</span> <span class="dv">1000</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>text, ttft_ms, total_ms <span class="op">=</span> asyncio.run(</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    consume(<span class="st">"hi"</span>, [<span class="st">"Stream"</span>, <span class="st">"ing"</span>, <span class="st">" cuts"</span>, <span class="st">" perceived"</span>, <span class="st">" latency"</span>, <span class="st">"."</span>])</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">repr</span>(text), <span class="ss">f"TTFT </span><span class="sc">{</span>ttft_ms<span class="sc">:.0f}</span><span class="ss"> ms"</span>, <span class="ss">f"total </span><span class="sc">{</span>total_ms<span class="sc">:.0f}</span><span class="ss"> ms"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Measured output on this machine (one run; timing jitters by a few milliseconds):</p>
<pre class="text"><code>'Streaming cuts perceived latency.' TTFT 301 ms total 788 ms</code></pre>
<p>Read the two numbers together. The full answer took 788 ms to generate, but the user saw text at 301 ms. In a non-streaming client, that first text would have waited the full 788 ms. That gap is the whole point.</p>
<p><strong>Example 2 — the perceived-latency win scales with answer length.</strong> Longer answers make streaming more valuable, because TTFT stays roughly constant while total time grows.</p>
<p>At 40 tokens per second with a 0.30 s TTFT, total time is <code>TTFT + (tokens - 1) / rate</code>:</p>
<pre class="text"><code>answer length     streaming TTFT     non-streaming first text (total)
50 tokens         0.30 s             1.5 s
300 tokens        0.30 s             7.8 s
1000 tokens       0.30 s             25.3 s</code></pre>
<p>The first row is a short reply where streaming hardly matters. The last row is an agent writing a long report, where non-streaming feels broken. Streaming is most valuable exactly where answers are long.</p>
<p><strong>Example 3 — assemble a tool call split across chunks.</strong> This is the part that surprises people. The function name and the JSON arguments arrive in pieces.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>chunks <span class="op">=</span> [</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"choices"</span>: [{<span class="st">"delta"</span>: {<span class="st">"content"</span>: <span class="st">"Check"</span>}}]},</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"choices"</span>: [{<span class="st">"delta"</span>: {<span class="st">"content"</span>: <span class="st">"ing"</span>}}]},</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"choices"</span>: [{<span class="st">"delta"</span>: {<span class="st">"content"</span>: <span class="st">" weather"</span>}}]},</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"choices"</span>: [{<span class="st">"delta"</span>: {<span class="st">"tool_calls"</span>: [{<span class="st">"index"</span>: <span class="dv">0</span>, <span class="st">"id"</span>: <span class="st">"call_1"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"function"</span>: {<span class="st">"name"</span>: <span class="st">"get_weather"</span>, <span class="st">"arguments"</span>: <span class="st">'{"ci'</span>}}]}}]},</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"choices"</span>: [{<span class="st">"delta"</span>: {<span class="st">"tool_calls"</span>: [{<span class="st">"index"</span>: <span class="dv">0</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"function"</span>: {<span class="st">"arguments"</span>: <span class="st">'ty": "Pune"}'</span>}}]}}]},</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>text <span class="op">=</span> <span class="st">""</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>tool <span class="op">=</span> {<span class="st">"id"</span>: <span class="va">None</span>, <span class="st">"name"</span>: <span class="st">""</span>, <span class="st">"arguments"</span>: <span class="st">""</span>}</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> chunks:</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> c[<span class="st">"choices"</span>][<span class="dv">0</span>][<span class="st">"delta"</span>]</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    text <span class="op">+=</span> d.get(<span class="st">"content"</span>) <span class="kw">or</span> <span class="st">""</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> tc <span class="kw">in</span> d.get(<span class="st">"tool_calls"</span>, []):</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>        tool[<span class="st">"id"</span>] <span class="op">=</span> tc.get(<span class="st">"id"</span>, tool[<span class="st">"id"</span>])</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>        fn <span class="op">=</span> tc.get(<span class="st">"function"</span>, {})</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>        tool[<span class="st">"name"</span>] <span class="op">+=</span> fn.get(<span class="st">"name"</span>, <span class="st">""</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>        tool[<span class="st">"arguments"</span>] <span class="op">+=</span> fn.get(<span class="st">"arguments"</span>, <span class="st">""</span>)</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"text:"</span>, <span class="bu">repr</span>(text))</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"tool:"</span>, tool)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Measured output:</p>
<pre class="text"><code>text: 'Checking weather'
tool: {'id': 'call_1', 'name': 'get_weather', 'arguments': '{"city": "Pune"}'}</code></pre>
<p>Only the finished <code>arguments</code> string is valid JSON. Parsing on the first fragment would raise a <code>JSONDecodeError</code>, which is a classic streaming bug.</p>
<p><strong>Example 4 — an error in the middle of a stream.</strong> The stream can fail after it has already produced useful text. Good clients keep the partial result.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> asyncio</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="cf">async</span> <span class="kw">def</span> with_partial_failure(prompt, tokens):</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">await</span> asyncio.sleep(<span class="fl">0.01</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, tok <span class="kw">in</span> <span class="bu">enumerate</span>(tokens):</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> i <span class="op">==</span> <span class="dv">2</span>:</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>            <span class="cf">raise</span> <span class="pp">ConnectionError</span>(<span class="st">"upstream closed the stream"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">yield</span> tok</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">await</span> asyncio.sleep(<span class="fl">0.01</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="cf">async</span> <span class="kw">def</span> collect_with_recovery(prompt, tokens):</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    pieces <span class="op">=</span> []</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">async</span> <span class="cf">for</span> tok <span class="kw">in</span> with_partial_failure(prompt, tokens):</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>            pieces.append(tok)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">ConnectionError</span> <span class="im">as</span> e:</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">""</span>.join(pieces), <span class="ss">f"partial + error: </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">""</span>.join(pieces), <span class="st">"complete"</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>text, status <span class="op">=</span> asyncio.run(collect_with_recovery(<span class="st">"hi"</span>, [<span class="st">"a"</span>, <span class="st">"b"</span>, <span class="st">"c"</span>, <span class="st">"d"</span>]))</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">repr</span>(text), <span class="st">"|"</span>, status)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Measured output:</p>
<pre class="text"><code>'ab' | partial + error: upstream closed the stream</code></pre>
<p>The client shows <code>ab</code>, then a retry or an error notice. Discarding <code>ab</code> and starting over wastes work and can make the answer worse.</p>
<p><strong>Example 5 — cancellation.</strong> A user closes the page. Stop reading and free the connection.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> asyncio</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="cf">async</span> <span class="kw">def</span> cancellable(prompt, tokens):</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">await</span> asyncio.sleep(<span class="fl">0.01</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> tok <span class="kw">in</span> tokens:</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">yield</span> tok</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">await</span> asyncio.sleep(<span class="fl">0.10</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="cf">async</span> <span class="kw">def</span> main():</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    pieces <span class="op">=</span> []</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">async</span> <span class="cf">for</span> tok <span class="kw">in</span> cancellable(<span class="st">"hi"</span>, [<span class="st">"x"</span>, <span class="st">"y"</span>, <span class="st">"z"</span>, <span class="st">"w"</span>, <span class="st">"v"</span>]):</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>            pieces.append(tok)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="bu">len</span>(pieces) <span class="op">==</span> <span class="dv">2</span>:</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>                <span class="cf">raise</span> asyncio.CancelledError</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> asyncio.CancelledError:</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"cancelled after:"</span>, <span class="bu">repr</span>(<span class="st">""</span>.join(pieces)))</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>asyncio.run(main())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Measured output:</p>
<pre class="text"><code>cancelled after: 'xy'</code></pre>
<p>The generator stops where it was cancelled. In a real system this translates into a saved connection and less billed generation.</p>
</section>
<section id="in-production" class="level2">
<h2 class="anchored" data-anchor-id="in-production">In production</h2>
<ul>
<li><strong>Measure TTFT separately from total latency.</strong> A single “latency” number hides the two things users actually feel. Track p50 and p95 for both, and alert on TTFT regressions.</li>
<li><strong>The first chunk is often not content.</strong> Many providers send a chunk that only sets the assistant role. Count TTFT from the first chunk with actual text, or your metric will look better than reality.</li>
<li><strong>Proxies silently break streaming.</strong> A load balancer, CDN, or API gateway that buffers responses collects the whole answer before forwarding it. Disable buffering for streamed routes, and test through the real network path, not just locally.</li>
<li><strong>Handle <code>finish_reason: "length"</code>.</strong> A truncated answer is worse than an error because it looks complete. Log the reason and surface a clear “response was cut off” path.</li>
<li><strong>Always keep partial text on failure.</strong> A mid-stream error is normal, not exotic. Persist the deltas you received so you can retry, resume, or show what you have.</li>
<li><strong>Cancel when the user leaves.</strong> Without cancellation, an abandoned request keeps generating and billing. Tie the HTTP request lifetime to the generation lifetime.</li>
<li><strong>Do not parse partial JSON with <code>json.loads</code>.</strong> Either wait for the stream to finish, use an incremental parser, or use the provider’s structured-streaming helper that assembles the object for you.</li>
<li><strong>Tool-call fragments must be concatenated by index.</strong> Parallel tool calls are interleaved in one stream, keyed by <code>index</code>. Group by index before joining, or you will merge two different calls.</li>
<li><strong>SSE needs a heartbeat for long gaps.</strong> If the model thinks for many seconds before the first token, some proxies drop an idle connection. Providers send comment lines like <code>: ping</code> to keep it alive.</li>
<li><strong>Report usage explicitly.</strong> With streaming, token usage is not in the default response. Enable the usage option or count tokens yourself, or your cost dashboard will be wrong.</li>
</ul>
</section>
<section id="interview-questions" class="level2">
<h2 class="anchored" data-anchor-id="interview-questions">Interview questions</h2>
<section id="does-streaming-make-the-model-generate-faster" class="level3">
<h3 class="anchored" data-anchor-id="does-streaming-make-the-model-generate-faster">1. Does streaming make the model generate faster?</h3>
<p><strong>Answer.</strong> No.&nbsp;The model still produces the same tokens in the same order at the same speed. Streaming only changes <em>when</em> each token reaches the client. It improves time-to-first-token dramatically and leaves total generation time essentially unchanged.</p>
<p><strong>Follow-up: “Then why do users say it feels faster?”</strong> Because perceived latency is dominated by how long the screen stays empty. Streaming replaces one long wait with a short one followed by visible progress.</p>
<p><strong>Trap.</strong> Claiming streaming reduces compute cost. It usually adds a little per-chunk overhead, and the total tokens generated are the same unless the user cancels.</p>
</section>
<section id="what-is-time-to-first-token-and-what-determines-it" class="level3">
<h3 class="anchored" data-anchor-id="what-is-time-to-first-token-and-what-determines-it">2. What is time-to-first-token, and what determines it?</h3>
<p><strong>Answer.</strong> TTFT is the delay from sending the request to receiving the first content token. It is made of network time, queueing time at the provider, and <strong>prefill</strong> — the work of reading the entire prompt before generating. Longer prompts and busier servers mean higher TTFT. Prompt caching of a repeated prefix is the main lever to reduce it.</p>
<p><strong>Follow-up: “How does TTFT differ from inter-token latency?”</strong> TTFT is a one-time startup cost; inter-token latency is the steady-state delay between later tokens. Total latency is roughly TTFT plus tokens times inter-token latency.</p>
<p><strong>Trap.</strong> Measuring TTFT from the first chunk you receive. That chunk may carry only the assistant role and no text, which flatters the number.</p>
</section>
<section id="what-technology-carries-a-streamed-response" class="level3">
<h3 class="anchored" data-anchor-id="what-technology-carries-a-streamed-response">3. What technology carries a streamed response?</h3>
<p><strong>Answer.</strong> Server-sent events: a one-way stream of text events over an ordinary HTTP connection, with a <code>text/event-stream</code> content type. Each event is a <code>data:</code> line followed by a blank line, and HTTP chunked transfer encoding lets the body arrive in pieces of unknown total length. WebSockets would also work but are unnecessary because the traffic is one-directional.</p>
<p><strong>Follow-up: “What does <code>data: [DONE]</code> mean?”</strong> It is an OpenAI convention marking the end of the stream. It is not part of the SSE standard; other providers close the connection instead.</p>
<p><strong>Trap.</strong> Saying SSE is WebSockets, or that it is a special binary protocol. It is plain text over HTTP.</p>
</section>
<section id="how-do-you-handle-a-tool-call-when-streaming" class="level3">
<h3 class="anchored" data-anchor-id="how-do-you-handle-a-tool-call-when-streaming">4. How do you handle a tool call when streaming?</h3>
<p><strong>Answer.</strong> The model streams the tool name and the JSON arguments as string fragments, keyed by an index. You concatenate the fragments per index until the stream ends, then parse the joined string as JSON and execute the tool. You must not parse a fragment on its own, because it is usually incomplete JSON.</p>
<p><strong>Follow-up: “What about parallel tool calls?”</strong> They are interleaved in the same stream with different <code>index</code> values. You accumulate a separate buffer per index and only dispatch once all are complete.</p>
<p><strong>Trap.</strong> Calling <code>json.loads</code> on each delta. It raises on the first fragment and looks like a provider bug when it is a client bug.</p>
</section>
<section id="what-goes-wrong-when-streaming-fails-halfway" class="level3">
<h3 class="anchored" data-anchor-id="what-goes-wrong-when-streaming-fails-halfway">5. What goes wrong when streaming fails halfway?</h3>
<p><strong>Answer.</strong> The client has partial text and no final <code>finish_reason</code>. The right behaviour is to keep the partial text, record that the stream was incomplete, and then retry, resume from the last token, or show a clear error. Throwing away the partial output wastes tokens the user already paid for and gives a worse experience.</p>
<p><strong>Follow-up: “Can you resume a stream?”</strong> Not with the standard APIs. You would resend the conversation so far and ask the model to continue, which costs the prompt tokens again. True token-level resume is not exposed.</p>
<p><strong>Trap.</strong> Treating a mid-stream error as a total failure. Many failures happen after a useful prefix has already arrived.</p>
</section>
<section id="how-do-you-cancel-a-running-stream-and-why-does-it-matter" class="level3">
<h3 class="anchored" data-anchor-id="how-do-you-cancel-a-running-stream-and-why-does-it-matter">6. How do you cancel a running stream, and why does it matter?</h3>
<p><strong>Answer.</strong> You close the connection, which signals the provider to stop generating. It matters because abandoned streams keep consuming GPU time and billing. Closing is fast but not instant: a few tokens may already be in flight, so you may be billed slightly past the cancellation point.</p>
<p><strong>Follow-up: “How do you wire that up in a web app?”</strong> Tie the request lifetime to the generation: when the client disconnects, cancel the async task that is reading the stream, and close the upstream connection in a <code>finally</code> or context manager.</p>
<p><strong>Trap.</strong> Forgetting to cancel at all, so every closed tab leaves a generation running to completion.</p>
</section>
<section id="how-does-streaming-interact-with-structured-json-output" class="level3">
<h3 class="anchored" data-anchor-id="how-does-streaming-interact-with-structured-json-output">7. How does streaming interact with structured JSON output?</h3>
<p><strong>Answer.</strong> Providers can stream the JSON, but the bytes arrive as an incomplete document, so you cannot parse each chunk. You either buffer until the stream completes and parse once, use an incremental JSON parser that yields partial objects, or use the provider’s structured-streaming helper, which accumulates the object and returns the finished model.</p>
<p><strong>Follow-up: “When would you stream structured output at all?”</strong> When the JSON is large and you want to show progress, such as filling a table row by row. For small objects, buffering and parsing once is simpler and safer.</p>
<p><strong>Trap.</strong> Assuming streaming and strict JSON schema are mutually exclusive. They work together; the constraint is on the <em>client parser</em>, not the model.</p>
</section>
<section id="what-metrics-would-you-put-on-a-streaming-endpoint" class="level3">
<h3 class="anchored" data-anchor-id="what-metrics-would-you-put-on-a-streaming-endpoint">8. What metrics would you put on a streaming endpoint?</h3>
<p><strong>Answer.</strong> Time-to-first-token, inter-token latency, total latency, tokens per second, cancellation rate, and incomplete-stream rate, each with p50 and p95. Also track <code>finish_reason</code> distribution, because a rising <code>length</code> rate means answers are being truncated. Compare all of them against a non-streaming baseline if you ever switch.</p>
<p><strong>Follow-up: “Which metric best predicts user satisfaction?”</strong> TTFT, especially for short replies. Once text is moving, users tolerate a slow tail far better than a slow start.</p>
<p><strong>Trap.</strong> Reporting average latency only. Averages hide the p95 stalls that users actually complain about.</p>
</section>
</section>
<section id="remember-this" class="level2">
<h2 class="anchored" data-anchor-id="remember-this">Remember this</h2>
<ul>
<li>Streaming changes <strong>when</strong> tokens arrive, not <strong>how fast</strong> they are generated.</li>
<li><strong>TTFT is perceived latency.</strong> Optimise prefill, network, and prompt caching to improve it.</li>
<li>SSE over HTTP carries the tokens: <code>data:</code> lines separated by blank lines, ending at <code>[DONE]</code> or a closed socket.</li>
<li><strong>Append deltas; never replace with them.</strong> Tool-call arguments arrive as fragments to concatenate by index.</li>
<li><strong>Handle partial results, errors, and cancellation</strong> as first-class cases, because streams fail mid-flight by design.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ranjeet-h\.github\.io\/agentic-ai-engineer-book");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../phase-02-llm-fundamentals/17-function-and-tool-calling.html" class="pagination-link" aria-label="Function and Tool Calling">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Function and Tool Calling</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../phase-02-llm-fundamentals/19-prompt-design-and-system-prompts.html" class="pagination-link" aria-label="Prompt Design and System Prompts">
        <span class="nav-page-text"><span class="chapter-title">Prompt Design and System Prompts</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>