<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Agent Memory: Short-Term and Working – Agentic AI Engineering Study Book</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../phase-04-agentic-ai-engineering/05-agent-memory-long-term-episodic-semantic.html" rel="next">
<link href="../phase-04-agentic-ai-engineering/03-tool-execution-and-result-validation.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-89355393b13d2c35defd37e977706fc2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-54623c61267def5306c3b17f0a722ca1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../assets/fonts/fonts.css">
<link rel="stylesheet" href="../styles/custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../phase-04-agentic-ai-engineering/index.html">Phase 4 — Agentic AI Engineering</a></li><li class="breadcrumb-item"><a href="../phase-04-agentic-ai-engineering/04-agent-memory-short-term-and-working.html"><span class="chapter-title">Agent Memory: Short-Term and Working</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Agentic AI Engineering Study Book</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Study architecture</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-01-production-python/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 — Production Python</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/01-type-hints.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Type Hints</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/02-dataclasses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dataclasses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/03-pydantic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pydantic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/04-decorators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Decorators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/05-iterators-and-generators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Iterators and Generators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/06-context-managers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Managers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/07-exception-handling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Exception Handling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/08-file-handling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">File Handling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/09-async-and-asyncio.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Async and asyncio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/10-threads-and-processes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Threads and Processes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/11-concurrency-patterns.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Concurrency Patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/12-packaging-and-virtual-environments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Packaging and Virtual Environments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/13-dependency-management.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dependency Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/14-logging.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/15-configuration-management.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Configuration Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/16-pytest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">pytest</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/17-mocking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mocking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/18-profiling-and-performance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Profiling and Performance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/19-fastapi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">FastAPI</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/20-sqlalchemy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">SQLAlchemy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/21-alembic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Alembic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/22-postgresql.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">PostgreSQL</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/23-redis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Redis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/24-authentication-and-authorization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Authentication and Authorization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/25-background-jobs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Background Jobs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/26-rate-limiting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Rate Limiting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/27-api-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">API Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/28-dockerizing-python-applications.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dockerizing Python Applications</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/29-cicd-for-python-services.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">CI/CD for Python Services</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-02-llm-fundamentals/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 2 — LLM and Generative AI Fundamentals</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/01-how-ml-and-neural-networks-work.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How Machine Learning and Neural Networks Work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/02-tensors-and-pytorch.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tensors and PyTorch</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/03-forward-pass-and-backpropagation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Forward Pass and Backpropagation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/04-attention-and-self-attention.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Attention and Self-Attention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/05-the-transformer-architecture.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Transformer Architecture</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/06-tokenization-and-tokens.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tokenization and Tokens</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/07-embeddings.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Embeddings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/08-context-windows-and-kv-cache.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Windows and the KV Cache</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/09-logits-softmax-next-token-prediction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logits, Softmax, and Next-Token Prediction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/10-sampling-temperature-top-k-top-p.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sampling: Temperature, Top-K, Top-P</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/11-training-vs-inference-and-batching.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Training vs Inference and Batching</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/12-pretraining-finetuning-instruction-tuning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pretraining, Fine-Tuning, and Instruction Tuning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/13-rlhf-and-preference-alignment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RLHF and Preference Alignment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/14-lora-qlora-peft.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Parameter-Efficient Fine-Tuning: LoRA, QLoRA, PEFT</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/15-numeric-precision-and-quantization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Numeric Precision and Quantization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/16-structured-outputs-and-json-schema.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Structured Outputs and JSON Schema</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/17-function-and-tool-calling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Function and Tool Calling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/18-streaming-responses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Streaming Responses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/19-prompt-design-and-system-prompts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Prompt Design and System Prompts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/20-context-engineering.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Engineering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/21-hallucinations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hallucinations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/22-prompt-injection-and-context-poisoning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Prompt Injection and Context Poisoning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/23-model-comparison-and-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Model Comparison and Selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/24-provider-apis-openai-anthropic-gemini.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Provider APIs: OpenAI, Anthropic, Gemini</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/25-open-source-models-and-hugging-face.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Open-Source Models and Hugging Face</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-03-rag-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 3 — RAG Engineering</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/01-rag-architecture.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Architecture</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/02-document-ingestion-and-parsing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Document Ingestion and Parsing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/03-chunking-strategies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chunking Strategies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/04-metadata-extraction-and-filtering.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Metadata Extraction and Filtering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/05-embedding-models-and-dimensions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Embedding Models and Dimensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/06-similarity-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Similarity Metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/07-vector-databases-and-ann-indexes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Vector Databases and ANN Indexes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/08-postgresql-pgvector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">PostgreSQL pgvector</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/09-dense-and-sparse-retrieval.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dense and Sparse Retrieval</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/10-hybrid-search.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hybrid Search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/11-query-transformation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Query Transformation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/12-reranking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reranking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/13-context-construction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Construction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/14-citations-and-grounded-generation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Citations and Grounded Generation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/15-knowledge-base-versioning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Knowledge-Base Versioning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/16-rag-caching-and-latency.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Caching and Latency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/17-retrieval-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Retrieval Metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/18-generation-quality-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Generation Quality Metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/19-rag-evaluation-and-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Evaluation and Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/20-multi-tenant-rag.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multi-Tenant RAG</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/21-rag-security-and-access-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Security and Access Control</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-04-agentic-ai-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 4 — Agentic AI Engineering</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/01-what-an-ai-agent-is.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">What an AI Agent Is</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/02-the-agent-loop.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Agent Loop</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/03-tool-execution-and-result-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tool Execution and Result Validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/04-agent-memory-short-term-and-working.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Agent Memory: Short-Term and Working</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/05-agent-memory-long-term-episodic-semantic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Agent Memory: Long-Term, Episodic, and Semantic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/06-planning-decomposition-and-routing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Planning, Decomposition, and Routing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/07-reflection-and-self-correction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reflection and Self-Correction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/08-retries-termination-and-loop-detection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Retries, Termination, and Loop Detection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/09-state-management-and-persistence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">State Management and Persistence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/10-checkpointing-and-durable-execution.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Checkpointing and Durable Execution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/11-human-in-the-loop-and-approvals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Human-in-the-Loop and Approvals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/12-guardrails.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Guardrails</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/13-structured-agent-outputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Structured Agent Outputs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/14-tool-schemas-and-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tool Schemas and Selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/15-tool-permissions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tool Permissions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/16-parallel-and-conditional-workflows.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Parallel and Conditional Workflows</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/17-long-running-and-background-agents.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Long-Running and Background Agents</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/18-langgraph-graphs-and-state.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">LangGraph: Graphs and State</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/19-langgraph-checkpoints-interrupts-subgraphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">LangGraph: Checkpoints, Interrupts, and Subgraphs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/20-openai-agents-sdk.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">OpenAI Agents SDK</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/21-agent-orchestration-patterns.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Agent Orchestration Patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/22-agent-reliability.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Agent Reliability</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#why-this-exists" id="toc-why-this-exists" class="nav-link active" data-scroll-target="#why-this-exists">Why this exists</a></li>
  <li><a href="#start-from-zero" id="toc-start-from-zero" class="nav-link" data-scroll-target="#start-from-zero">Start from zero</a></li>
  <li><a href="#the-core-idea" id="toc-the-core-idea" class="nav-link" data-scroll-target="#the-core-idea">The core idea</a></li>
  <li><a href="#how-it-works" id="toc-how-it-works" class="nav-link" data-scroll-target="#how-it-works">How it works</a></li>
  <li><a href="#the-syntax-you-will-use" id="toc-the-syntax-you-will-use" class="nav-link" data-scroll-target="#the-syntax-you-will-use">The syntax you will use</a></li>
  <li><a href="#examples-simple-to-real" id="toc-examples-simple-to-real" class="nav-link" data-scroll-target="#examples-simple-to-real">Examples: simple to real</a></li>
  <li><a href="#in-production" id="toc-in-production" class="nav-link" data-scroll-target="#in-production">In production</a></li>
  <li><a href="#interview-questions" id="toc-interview-questions" class="nav-link" data-scroll-target="#interview-questions">Interview questions</a></li>
  <li><a href="#remember-this" id="toc-remember-this" class="nav-link" data-scroll-target="#remember-this">Remember this</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../phase-04-agentic-ai-engineering/index.html">Phase 4 — Agentic AI Engineering</a></li><li class="breadcrumb-item"><a href="../phase-04-agentic-ai-engineering/04-agent-memory-short-term-and-working.html"><span class="chapter-title">Agent Memory: Short-Term and Working</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Agent Memory: Short-Term and Working</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Interview answer (say this first).</strong> Short-term memory is the conversation buffer — the recent user and assistant messages kept in the context window. Working memory is the scratchpad the agent is actively using right now: its plan, current step, and the facts it has gathered. Both live inside a finite token budget, so the real engineering is measuring that budget and deciding every turn what to keep, what to summarise, and what to drop. Long-term memory is different: it lives outside the context and is retrieved into it when relevant.</p>
</blockquote>
<section id="why-this-exists" class="level2">
<h2 class="anchored" data-anchor-id="why-this-exists">Why this exists</h2>
<p>An agent loop only works if the model can see enough of the past to make a good next decision. That sounds trivial until you run a real task. A 40-turn research agent that appends every message and every tool result ends up sending a huge prompt on every turn. Three things break at once:</p>
<ul>
<li><strong>The context window fills up.</strong> Once the prompt exceeds the model’s limit, the request errors, or your provider silently truncates and the agent loses instructions.</li>
<li><strong>Cost and latency climb.</strong> Input tokens are charged on every turn, so the bill grows with the square of the turns. Latency climbs with prompt length too.</li>
<li><strong>Quality drops.</strong> Models attend unevenly to long prompts. Instructions buried in the middle are easier to miss, an effect often called “lost in the middle.” Adding more text can make the agent dumber.</li>
</ul>
<p>There is a second, separate failure. Even when the context fits, the agent loses its <strong>plan</strong>. If the plan exists only as an implicit pattern in the transcript, a long chain of tool results can bury it, and the model starts repeating work or forgetting a constraint. Production agents keep the plan in explicit <strong>working memory</strong> and rewrite it each turn.</p>
<p>So memory is not “store everything.” It is a budgeting problem with three questions:</p>
<ol type="1">
<li>What must stay for the task to succeed?</li>
<li>What can be summarised without losing the decision-relevant facts?</li>
<li>What can be dropped entirely because it can be retrieved again?</li>
</ol>
<p>This page covers the two memories that live inside the context — short-term and working. Long-term, episodic, and semantic memory live outside the window and get their own page.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The one-sentence purpose.</strong> Memory engineering is managing a finite token budget so the model always sees the small amount of information it needs, and never pays for the large amount it does not.</p>
</div>
</div>
</section>
<section id="start-from-zero" class="level2">
<h2 class="anchored" data-anchor-id="start-from-zero">Start from zero</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Word</th>
<th>Plain meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Memory</strong></td>
<td>Information an agent carries forward instead of recomputing or re-fetching.</td>
</tr>
<tr class="even">
<td><strong>Short-term memory</strong></td>
<td>The live conversation: recent user, assistant, and tool messages, in order.</td>
</tr>
<tr class="odd">
<td><strong>Working memory</strong></td>
<td>The agent’s active scratchpad: current plan, step, and gathered facts.</td>
</tr>
<tr class="even">
<td><strong>Long-term memory</strong></td>
<td>Stored information outside the context, retrieved when relevant.</td>
</tr>
<tr class="odd">
<td><strong>Episodic memory</strong></td>
<td>Records of past events and runs, such as “last time we refunded order 42.”</td>
</tr>
<tr class="even">
<td><strong>Semantic memory</strong></td>
<td>Durable facts and knowledge, such as policies and product details.</td>
</tr>
<tr class="odd">
<td><strong>Procedural memory</strong></td>
<td>How-to knowledge, such as a playbook or a trained skill.</td>
</tr>
<tr class="even">
<td><strong>Context window</strong></td>
<td>The maximum tokens the model can consider in one call.</td>
</tr>
<tr class="odd">
<td><strong>Token</strong></td>
<td>A chunk of text, roughly three-quarters of a word in English. The unit of cost and limits.</td>
</tr>
<tr class="even">
<td><strong>Token budget</strong></td>
<td>The number of tokens you allow yourself to send, below the hard limit.</td>
</tr>
<tr class="odd">
<td><strong>Conversation buffer</strong></td>
<td>The raw list of messages kept for the current task.</td>
</tr>
<tr class="even">
<td><strong>Scratchpad</strong></td>
<td>A field where the agent writes plan and notes, separate from the chat.</td>
</tr>
<tr class="odd">
<td><strong>State</strong></td>
<td>Everything the agent knows: messages, plan, step, gathered facts, results.</td>
</tr>
<tr class="even">
<td><strong>Trimming</strong></td>
<td>Dropping the oldest messages until the context fits the budget.</td>
</tr>
<tr class="odd">
<td><strong>Eviction</strong></td>
<td>Removing a specific item from memory, chosen by policy.</td>
</tr>
<tr class="even">
<td><strong>Summarisation</strong></td>
<td>Replacing several messages with one shorter summary.</td>
</tr>
<tr class="odd">
<td><strong>Compaction</strong></td>
<td>Summarising older context while keeping recent turns verbatim.</td>
</tr>
<tr class="even">
<td><strong>Rolling window</strong></td>
<td>Keeping only the last N turns, always dropping the oldest.</td>
</tr>
<tr class="odd">
<td><strong>Memory write</strong></td>
<td>Deciding that a fact is worth storing outside the context.</td>
</tr>
<tr class="even">
<td><strong>Memory read</strong></td>
<td>Retrieving a stored fact back into the context.</td>
</tr>
<tr class="odd">
<td><strong>Recency bias</strong></td>
<td>The tendency to weight the newest text most heavily; useful and dangerous.</td>
</tr>
<tr class="even">
<td><strong>Lost in the middle</strong></td>
<td>The observed drop in attention for content in the middle of a long prompt.</td>
</tr>
</tbody>
</table>
<p>Two clarifications:</p>
<ul>
<li><strong>Short-term vs working memory.</strong> Short-term memory is the transcript; it is append-only until you trim it. Working memory is structured and deliberately rewritten: a plan, a step counter, a facts table. They overlap, but they are managed differently.</li>
<li><strong>Memory vs state.</strong> State is the complete picture, and it can live outside the model in your database. Memory is the part brought into the prompt. Persist state durably; load only a slice of it as memory.</li>
</ul>
</section>
<section id="the-core-idea" class="level2">
<h2 class="anchored" data-anchor-id="the-core-idea">The core idea</h2>
<p>Picture a <strong>desk, a whiteboard, and a filing cabinet</strong>.</p>
<ul>
<li>The <strong>desk</strong> is working memory. It holds only what you are using right now: the plan, the current step, the facts you just gathered. A tidy desk makes you fast; a cluttered one slows you down.</li>
<li>The <strong>whiteboard</strong> is short-term memory. It records the recent back-and-forth so you can follow the conversation. It gets wiped and rewritten as the session goes on.</li>
<li>The <strong>filing cabinet</strong> is long-term memory. It holds everything, but you fetch a folder only when you need it. You would never staple the whole cabinet to the desk.</li>
</ul>
<p>The engineering is deciding what belongs on the desk at each moment, and the constraint is the <strong>token budget</strong>. The filing cabinet is cheap; the desk is expensive.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    G["Goal + system prompt&lt;br/&gt;always kept"] --&gt; C["Context assembler"]
    W["Working memory&lt;br/&gt;plan, step, facts"] --&gt; C
    R["Recent turns&lt;br/&gt;kept verbatim"] --&gt; C
    S["Summary of older turns&lt;br/&gt;compacted"] --&gt; C
    L["Retrieved long-term memory&lt;br/&gt;only when relevant"] --&gt; C
    C --&gt; T{"Under token budget?"}
    T --&gt;|"yes"| M["Model call"]
    T --&gt;|"no"| X["Trim or compact, then retry"]
    X --&gt; C
    M --&gt; U["New turn appended"]
    U --&gt; W
    U --&gt; R
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Every block feeding the assembler is a choice. The goal and system prompt are non-negotiable. Working memory is small and high-value. Recent turns are kept verbatim because they are most relevant. Older turns are compressed. Long-term memory is pulled in only on demand.</p>
<p>The memory types and where they live:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Type</th>
<th>Holds</th>
<th>Lives where</th>
<th>Lifetime</th>
<th>Cost to keep</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Short-term</td>
<td>Recent conversation</td>
<td>Context window</td>
<td>Current task</td>
<td>High, grows each turn</td>
</tr>
<tr class="even">
<td>Working</td>
<td>Plan, step, facts</td>
<td>State, copied into context</td>
<td>Current task</td>
<td>Low, small and structured</td>
</tr>
<tr class="odd">
<td>Episodic</td>
<td>Past events and runs</td>
<td>Database, retrieved</td>
<td>Long</td>
<td>Low until retrieved</td>
</tr>
<tr class="even">
<td>Semantic</td>
<td>Durable facts, policies</td>
<td>Vector or keyword store</td>
<td>Long</td>
<td>Low until retrieved</td>
</tr>
<tr class="odd">
<td>Procedural</td>
<td>Playbooks, skills</td>
<td>Prompt or code</td>
<td>Long</td>
<td>Fixed prompt cost</td>
</tr>
</tbody>
</table>
<p>The key insight: <strong>only short-term memory grows by itself.</strong> Everything else is either fixed or fetched deliberately. So most context-budget work is managing the conversation buffer.</p>
</section>
<section id="how-it-works" class="level2">
<h2 class="anchored" data-anchor-id="how-it-works">How it works</h2>
<ol type="1">
<li><strong>Reserve room for the answer.</strong> The output tokens count against the same window. Decide the maximum answer size first, then the input budget is <code>window - max_output - safety margin</code>.</li>
<li><strong>Always include the system prompt and goal.</strong> These define the task and the rules. Never let them be trimmed, or the agent forgets its constraints.</li>
<li><strong>Include working memory.</strong> Add the plan, current step, and gathered facts as a compact structured block. Keep it small; it is the highest-value text you will send.</li>
<li><strong>Keep recent turns verbatim.</strong> The last few user and assistant messages are the most relevant, so they stay in full.</li>
<li><strong>Summarise older turns.</strong> When the buffer exceeds the budget, replace the oldest section with one summary message. Keep facts and decisions, drop pleasantries and repeated tool chatter.</li>
<li><strong>Truncate large tool results.</strong> A tool result that is only needed once can be reduced to the fields the model needs. Store the full result outside the context and keep a reference id.</li>
<li><strong>Retrieve long-term memory on demand.</strong> Search for facts relevant to the current step and add only the top few. Do not dump the whole store.</li>
<li><strong>Measure before sending.</strong> Count tokens with the model’s tokenizer and compare to the budget. Do this every turn, not once.</li>
<li><strong>Evict in a fixed order.</strong> Drop in this priority: oversized tool results, then old small talk, then summarise old turns, then trim oldest turns. Never evict the system prompt, current goal, or active plan.</li>
<li><strong>Write durable state outside the context.</strong> The full trajectory belongs in your database. The prompt is a view, not the source of truth.</li>
<li><strong>Log what changed.</strong> Record tokens before and after trimming or compaction, and which messages were dropped. Silent compaction hides bugs.</li>
<li><strong>Re-plan after compaction.</strong> After a big context change, ask the model to restate the plan so working memory stays aligned with the new context.</li>
</ol>
<p><strong>What to keep and what to drop.</strong> A simple policy that works well:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Keep</th>
<th>Drop or compress</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>System prompt and goal</td>
<td>Repeated greetings and acknowledgements</td>
</tr>
<tr class="even">
<td>Current plan and step</td>
<td>Old assistant reasoning that did not change the plan</td>
</tr>
<tr class="odd">
<td>Facts and decisions</td>
<td>Raw tool payloads already reduced to facts</td>
</tr>
<tr class="even">
<td>Errors still being worked on</td>
<td>Resolved errors and their retries</td>
</tr>
<tr class="odd">
<td>Recent turns verbatim</td>
<td>Old turns, compressed into a summary</td>
</tr>
<tr class="even">
<td>Constraints and permissions</td>
<td>Verbose examples already internalised</td>
</tr>
</tbody>
</table>
<p><strong>Measuring token growth.</strong> Use the model’s tokenizer, not a character guess.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> tiktoken</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>ENC <span class="op">=</span> tiktoken.get_encoding(<span class="st">"cl100k_base"</span>)   <span class="co"># one OpenAI encoding, not universal</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> tokens(messages):</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">len</span>(ENC.encode(json.dumps(messages)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Different model families use different tokenizers, so treat the exact number as an estimate and leave a margin. The growth pattern matters more than the last digit: context grows with every turn, and total billed input is the sum of every turn’s context.</p>
</section>
<section id="the-syntax-you-will-use" class="level2">
<h2 class="anchored" data-anchor-id="the-syntax-you-will-use">The syntax you will use</h2>
<p><strong>Count tokens for a message list.</strong> Encode the JSON form so role and overhead text are included.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> count(messages: <span class="bu">list</span>[<span class="bu">dict</span>]) <span class="op">-&gt;</span> <span class="bu">int</span>:</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">len</span>(ENC.encode(json.dumps(messages)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Trim the oldest messages to fit a budget.</strong> Keep the system message and the newest turns; drop from the front.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> trim_to_budget(messages, budget, keep_last<span class="op">=</span><span class="dv">6</span>):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    system <span class="op">=</span> [m <span class="cf">for</span> m <span class="kw">in</span> messages <span class="cf">if</span> m[<span class="st">"role"</span>] <span class="op">==</span> <span class="st">"system"</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    rest <span class="op">=</span> [m <span class="cf">for</span> m <span class="kw">in</span> messages <span class="cf">if</span> m[<span class="st">"role"</span>] <span class="op">!=</span> <span class="st">"system"</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    kept <span class="op">=</span> rest[<span class="op">-</span>keep_last:]                     <span class="co"># always keep recent turns</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">while</span> count(system <span class="op">+</span> kept) <span class="op">&gt;</span> budget <span class="kw">and</span> <span class="bu">len</span>(kept) <span class="op">&gt;</span> <span class="dv">1</span>:</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        kept <span class="op">=</span> kept[<span class="dv">1</span>:]                          <span class="co"># drop oldest first</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> system <span class="op">+</span> kept</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Compact older turns into one summary.</strong> Keep the last turns verbatim and replace the rest.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> compact(messages, keep_last<span class="op">=</span><span class="dv">2</span>):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    system <span class="op">=</span> [m <span class="cf">for</span> m <span class="kw">in</span> messages <span class="cf">if</span> m[<span class="st">"role"</span>] <span class="op">==</span> <span class="st">"system"</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    rest <span class="op">=</span> [m <span class="cf">for</span> m <span class="kw">in</span> messages <span class="cf">if</span> m[<span class="st">"role"</span>] <span class="op">!=</span> <span class="st">"system"</span>]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    old, recent <span class="op">=</span> rest[:<span class="op">-</span>keep_last], rest[<span class="op">-</span>keep_last:]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    summary <span class="op">=</span> <span class="st">"Summary: "</span> <span class="op">+</span> <span class="st">" | "</span>.join(</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>m[<span class="st">'role'</span>]<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span><span class="bu">str</span>(m.get(<span class="st">'content'</span>))[:<span class="dv">60</span>]<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> m <span class="kw">in</span> old)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> system <span class="op">+</span> [{<span class="st">"role"</span>: <span class="st">"system"</span>, <span class="st">"content"</span>: summary}] <span class="op">+</span> recent</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>A structured working-memory scratchpad.</strong> Small, explicit, and rewritten each turn.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>state <span class="op">=</span> {</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"goal"</span>: <span class="st">"Refund order 42 if it is late."</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"plan"</span>: [<span class="st">"lookup order"</span>, <span class="st">"check delivery date"</span>, <span class="st">"refund if late"</span>],</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"done"</span>: [],</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"facts"</span>: {},</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"step"</span>: <span class="dv">0</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Rebuild the prompt from state, not from the raw transcript.</strong> This keeps the prompt small and stable.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>prompt <span class="op">=</span> [</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"role"</span>: <span class="st">"system"</span>, <span class="st">"content"</span>: <span class="st">"Refund agent."</span>},</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"role"</span>: <span class="st">"user"</span>, <span class="st">"content"</span>: state[<span class="st">"goal"</span>]},</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"role"</span>: <span class="st">"system"</span>, <span class="st">"content"</span>: <span class="st">"Scratchpad: "</span> <span class="op">+</span> json.dumps(state)},</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>A rolling window with a guaranteed system prompt.</strong> The cheapest useful memory policy.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>recent <span class="op">=</span> [m <span class="cf">for</span> m <span class="kw">in</span> messages <span class="cf">if</span> m[<span class="st">"role"</span>] <span class="op">!=</span> <span class="st">"system"</span>]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>window <span class="op">=</span> [SYSTEM] <span class="op">+</span> recent[<span class="op">-</span><span class="dv">6</span>:]            <span class="co"># system + last 6 non-system messages</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Retrieve long-term memory only when it matches.</strong> Keyword overlap is enough to show the idea; embeddings scale it.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> retrieve(query, k<span class="op">=</span><span class="dv">2</span>):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    q <span class="op">=</span> <span class="bu">set</span>(query.lower().split())</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    scored <span class="op">=</span> [(<span class="bu">len</span>(q <span class="op">&amp;</span> <span class="bu">set</span>(item[<span class="st">"text"</span>].lower().split())), item)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>              <span class="cf">for</span> item <span class="kw">in</span> MEMORY_STORE]</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    scored <span class="op">=</span> [pair <span class="cf">for</span> pair <span class="kw">in</span> scored <span class="cf">if</span> pair[<span class="dv">0</span>] <span class="op">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    scored.sort(key<span class="op">=</span><span class="kw">lambda</span> pair: (<span class="op">-</span>pair[<span class="dv">0</span>], pair[<span class="dv">1</span>][<span class="st">"id"</span>]))</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> [item <span class="cf">for</span> _, item <span class="kw">in</span> scored[:k]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Persist the whole trajectory outside the context.</strong> The database keeps everything; the prompt keeps a view.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>DB.save_run(run_id, messages<span class="op">=</span>messages, state<span class="op">=</span>state, tokens<span class="op">=</span>tokens(messages))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="examples-simple-to-real" class="level2">
<h2 class="anchored" data-anchor-id="examples-simple-to-real">Examples: simple to real</h2>
<p><strong>Example 1 — context growth without management.</strong> Twelve turns of ordinary conversation were generated and measured. The buffer reached <strong>895 tokens</strong>, and every one of those tokens would be resent on the next turn.</p>
<pre class="text"><code>tokens after 12 turns : 895</code></pre>
<p>At this size it still fits most windows, but the pattern is linear and nothing stops it. Add tool results and the same run can reach six figures.</p>
<p><strong>Example 2 — trimming to a budget.</strong> The same buffer is trimmed to a 400-token budget, keeping the newest messages.</p>
<pre class="text"><code>after trim (budget 400): 238 tokens | messages: 7
trim keeps system      : True</code></pre>
<p>The buffer shrank from 895 to 238 tokens, a 73% reduction, and the system prompt survived. The cost is that older turns are gone; if they mattered, they needed to be summarised first.</p>
<p><strong>Example 3 — compaction instead of deletion.</strong> Compaction replaces old turns with one summary and keeps the last two turns in full.</p>
<pre class="text"><code>after compact : 382 tokens | messages: 4
compaction ratio : 0.427</code></pre>
<p>The context is 57% smaller and the important facts are still described. Compaction is slower and lossier than a pure window, because it needs a summarisation call, but it preserves decisions that trimming would silently delete.</p>
<p><strong>Example 4 — the sliding window is the cheapest option.</strong> Keeping only the last six messages, plus the system prompt, gives the same 238-token result as trimming, with no loop or measurement.</p>
<pre class="text"><code>sliding window tokens : 238</code></pre>
<p>Use it first. Move to budget-aware trimming and compaction only when the fixed window keeps dropping something the agent needs.</p>
<p><strong>Example 5 — working memory as a scratchpad.</strong> The plan and facts are held in a small structured state, not inferred from chat. This state reached only <strong>66 tokens</strong>; the rebuilt prompt with the goal and scratchpad was <strong>127 tokens</strong>.</p>
<pre class="text"><code>scratchpad: {"done": ["lookup order"], "facts": {"order_42": {"days_late": 0,
             "status": "payment_failed"}}, "goal": "Refund order 42...",
             "plan": ["check decline code", "page billing if insufficient_funds"],
             "step": 1}
scratchpad tokens: 66
rebuilt prompt tokens: 127</code></pre>
<p>Compare that with a 40-turn transcript. Explicit working memory is a fraction of the size and far more reliable, because the plan is stated rather than buried.</p>
<p><strong>Example 6 — retrieving long-term memory on demand.</strong> A query pulls only the matching records. The retrieved slice was <strong>42 tokens</strong>, and adding it brought the prompt to <strong>185 tokens</strong>.</p>
<pre class="text"><code>retrieved: ['m2', 'm1']
retrieved tokens: 42
with memory tokens: 185
empty query retrieval: []</code></pre>
<p>The query “order 42 payment failed refund” matched the two relevant records. An unrelated query matched nothing and added zero tokens, which is the point: long-term memory costs nothing until it is relevant.</p>
</section>
<section id="in-production" class="level2">
<h2 class="anchored" data-anchor-id="in-production">In production</h2>
<ul>
<li><strong>Budget the whole window, not just the input.</strong> Output tokens share the window with input. Reserve the maximum answer size plus a safety margin before you fill it.</li>
<li><strong>Count with the real tokenizer and leave a margin.</strong> Token counts differ by model family. A rough estimate plus a buffer is safer than trusting an exact number from another model.</li>
<li><strong>Keep the system prompt and active plan pinned.</strong> Never let trimming or compaction remove the rules or the current step. They are the cheapest and most important text.</li>
<li><strong>Prefer a rolling window first.</strong> It is simple and predictable. Add budget-aware trimming only when the window drops needed information.</li>
<li><strong>Summarise before you delete.</strong> Trimming is lossless only if the dropped content did not matter. Compaction keeps decisions at the cost of one summarisation call.</li>
<li><strong>Cap every tool result at the source.</strong> Truncate or select fields when the result is created. Large results are paid for on every later turn, not once.</li>
<li><strong>Store the full trajectory outside the context.</strong> The database is the source of truth; the prompt is a view. This also makes replay and debugging possible.</li>
<li><strong>Retrieve long-term memory with a budget.</strong> A retrieval that returns twenty documents destroys the context budget. Return a few, and rerank if needed.</li>
<li><strong>Beware recency bias.</strong> The newest text dominates, so a fresh tool result can override an older constraint. Restate critical rules near the end when it matters.</li>
<li><strong>Beware lost in the middle.</strong> Important instructions in the centre of a long prompt are easier to miss. Put the goal and constraints near the start, and the immediate task near the end.</li>
<li><strong>Re-plan after compaction.</strong> A summarised context can drift from the real plan. Ask the agent to restate the plan and continue from the scratchpad.</li>
<li><strong>Log memory decisions.</strong> Record tokens before and after, which messages were dropped, and what the summary contained. Silent compaction is a debugging nightmare.</li>
</ul>
</section>
<section id="interview-questions" class="level2">
<h2 class="anchored" data-anchor-id="interview-questions">Interview questions</h2>
<section id="what-is-the-difference-between-short-term-and-working-memory" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-difference-between-short-term-and-working-memory">1. What is the difference between short-term and working memory?</h3>
<p><strong>Answer.</strong> Short-term memory is the live conversation buffer: recent user, assistant, and tool messages kept in order. Working memory is the agent’s active scratchpad: the current plan, step, and gathered facts. Short-term memory grows by appending; working memory is structured and rewritten each turn. Both live in the context window, but they are managed differently.</p>
<p><strong>Follow-up: “Why not keep the plan in the transcript?”</strong> Because a long transcript buries it. A structured scratchpad keeps the plan small, explicit, and easy to restate.</p>
<p><strong>Trap.</strong> Treating them as the same thing and just appending everything. That is how a context window fills with noise.</p>
</section>
<section id="what-is-a-token-budget-and-how-do-you-set-it" class="level3">
<h3 class="anchored" data-anchor-id="what-is-a-token-budget-and-how-do-you-set-it">2. What is a token budget, and how do you set it?</h3>
<p><strong>Answer.</strong> It is the number of tokens you allow a request, below the model’s hard context limit. Set it by subtracting the maximum output tokens and a safety margin from the window size. Check the count before every call, because the budget is spent by input plus output together.</p>
<p><strong>Follow-up: “Why not just use the full window?”</strong> Output shares the window, provider limits and cost make the full window a trap, and quality often drops before the limit is reached.</p>
<p><strong>Trap.</strong> Counting only input tokens. The model’s answer is billed and limited from the same pool.</p>
</section>
<section id="how-do-trimming-summarisation-and-compaction-differ" class="level3">
<h3 class="anchored" data-anchor-id="how-do-trimming-summarisation-and-compaction-differ">3. How do trimming, summarisation, and compaction differ?</h3>
<p><strong>Answer.</strong> Trimming drops the oldest messages until the context fits. Summarisation replaces content with a shorter version. Compaction does both: older turns are summarised and recent turns are kept verbatim. Trimming is free but lossy; compaction costs a model call but preserves decisions.</p>
<p><strong>Follow-up: “When would you use each?”</strong> A rolling window for short tasks, trimming under a hard budget, and compaction for long runs where earlier decisions still matter.</p>
<p><strong>Trap.</strong> Compacting too aggressively. A summary that drops the reason for a decision causes the agent to undo its own work.</p>
</section>
<section id="what-should-always-survive-memory-management" class="level3">
<h3 class="anchored" data-anchor-id="what-should-always-survive-memory-management">4. What should always survive memory management?</h3>
<p><strong>Answer.</strong> The system prompt and rules, the current goal, the active plan and step, unresolved errors, and any permission or safety constraint. These are small and high value. Lose them and the agent loses its task or its limits.</p>
<p><strong>Follow-up: “What is safe to drop?”</strong> Acknowledgements, repeated reasoning that did not change the plan, resolved errors, and raw tool payloads already reduced to facts.</p>
<p><strong>Trap.</strong> Dropping constraints because they are old. Age does not make a rule irrelevant.</p>
</section>
<section id="how-do-you-measure-and-control-token-growth" class="level3">
<h3 class="anchored" data-anchor-id="how-do-you-measure-and-control-token-growth">5. How do you measure and control token growth?</h3>
<p><strong>Answer.</strong> Count tokens with the model’s tokenizer on the assembled prompt every turn, log the count, and compare it to the budget. Context grows with each turn, and total billed input is the sum of every turn’s context, so cost grows faster than the final size. Control it with smaller tool results, a rolling window, compaction, and cached prefixes.</p>
<p><strong>Follow-up: “What number would worry you?”</strong> A prompt that grows every turn with no cap, or one where tool results dominate the count. Both predict a hard stop or a runaway bill.</p>
<p><strong>Trap.</strong> Measuring only the final prompt size. The bill is the sum across turns.</p>
</section>
<section id="what-is-long-term-memory-in-an-agent" class="level3">
<h3 class="anchored" data-anchor-id="what-is-long-term-memory-in-an-agent">6. What is long-term memory in an agent?</h3>
<p><strong>Answer.</strong> Information stored outside the context and brought in only when relevant: episodic records of past runs, semantic facts and policies, and procedural playbooks. It is retrieved, not permanently present, so it costs nothing until it is used.</p>
<p><strong>Follow-up: “How do you decide what to write to long-term memory?”</strong> Write durable facts and decisions that will matter across runs, not raw transcripts. Storing everything makes retrieval worse.</p>
<p><strong>Trap.</strong> Confusing long-term memory with a bigger context window. Retrieval is selective; a bigger window is just more expensive text.</p>
</section>
<section id="what-is-lost-in-the-middle-and-how-does-it-affect-memory-design" class="level3">
<h3 class="anchored" data-anchor-id="what-is-lost-in-the-middle-and-how-does-it-affect-memory-design">7. What is “lost in the middle,” and how does it affect memory design?</h3>
<p><strong>Answer.</strong> It is the observed tendency for models to attend less to information in the middle of a long prompt than to the beginning and end. For memory design it means more context is not automatically better: put the goal and constraints near the start, the immediate task near the end, and keep the middle lean.</p>
<p><strong>Follow-up: “How do you handle a constraint that keeps getting ignored?”</strong> Restate it close to the current step, or move it into the tool or policy layer so it does not depend on attention at all.</p>
<p><strong>Trap.</strong> Fixing a forgotten instruction by adding more text. That usually makes attention worse.</p>
</section>
<section id="how-would-you-design-memory-for-a-long-running-agent" class="level3">
<h3 class="anchored" data-anchor-id="how-would-you-design-memory-for-a-long-running-agent">8. How would you design memory for a long-running agent?</h3>
<p><strong>Answer.</strong> Keep a durable state object outside the model with the goal, plan, step, facts, and full trajectory. Each turn, assemble a prompt from pinned instructions, compact working memory, recent turns, a summary of older turns, and retrieved long-term facts. Enforce a token budget, evict in a fixed order, and log every memory decision. After compaction, re-plan from the scratchpad.</p>
<p><strong>Follow-up: “What makes it resumable?”</strong> All state is outside the context, so a restarted process can rebuild the prompt from the database and continue.</p>
<p><strong>Trap.</strong> Keeping the only copy of state inside the conversation. A crash or a compaction then loses it forever.</p>
</section>
</section>
<section id="remember-this" class="level2">
<h2 class="anchored" data-anchor-id="remember-this">Remember this</h2>
<ul>
<li><strong>Short-term memory is the transcript; working memory is the scratchpad.</strong> Both live in the context window; only the transcript grows by itself.</li>
<li><strong>Budget the whole window</strong>, including output tokens, and measure with the real tokenizer every turn.</li>
<li><strong>Evict in a fixed order</strong> and never drop the system prompt, goal, plan, or safety constraints.</li>
<li><strong>Summarise before you delete</strong>; compaction preserves decisions that trimming silently loses.</li>
<li><strong>Keep the full trajectory outside the context.</strong> The database is the source of truth; the prompt is a view.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ranjeet-h\.github\.io\/agentic-ai-engineer-book");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../phase-04-agentic-ai-engineering/03-tool-execution-and-result-validation.html" class="pagination-link" aria-label="Tool Execution and Result Validation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Tool Execution and Result Validation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../phase-04-agentic-ai-engineering/05-agent-memory-long-term-episodic-semantic.html" class="pagination-link" aria-label="Agent Memory: Long-Term, Episodic, and Semantic">
        <span class="nav-page-text"><span class="chapter-title">Agent Memory: Long-Term, Episodic, and Semantic</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>