<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Retrieval Metrics – Agentic AI Engineering Study Book</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../phase-03-rag-engineering/18-generation-quality-metrics.html" rel="next">
<link href="../phase-03-rag-engineering/16-rag-caching-and-latency.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-89355393b13d2c35defd37e977706fc2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-54623c61267def5306c3b17f0a722ca1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../assets/fonts/fonts.css">
<link rel="stylesheet" href="../styles/custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../phase-03-rag-engineering/index.html">Phase 3 — RAG Engineering</a></li><li class="breadcrumb-item"><a href="../phase-03-rag-engineering/17-retrieval-metrics.html"><span class="chapter-title">Retrieval Metrics</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Agentic AI Engineering Study Book</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Study architecture</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-01-production-python/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 1 — Production Python</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/01-type-hints.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Type Hints</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/02-dataclasses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dataclasses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/03-pydantic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pydantic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/04-decorators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Decorators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/05-iterators-and-generators.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Iterators and Generators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/06-context-managers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Managers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/07-exception-handling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Exception Handling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/08-file-handling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">File Handling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/09-async-and-asyncio.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Async and asyncio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/10-threads-and-processes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Threads and Processes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/11-concurrency-patterns.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Concurrency Patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/12-packaging-and-virtual-environments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Packaging and Virtual Environments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/13-dependency-management.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dependency Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/14-logging.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/15-configuration-management.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Configuration Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/16-pytest.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">pytest</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/17-mocking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Mocking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/18-profiling-and-performance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Profiling and Performance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/19-fastapi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">FastAPI</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/20-sqlalchemy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">SQLAlchemy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/21-alembic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Alembic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/22-postgresql.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">PostgreSQL</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/23-redis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Redis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/24-authentication-and-authorization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Authentication and Authorization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/25-background-jobs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Background Jobs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/26-rate-limiting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Rate Limiting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/27-api-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">API Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/28-dockerizing-python-applications.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dockerizing Python Applications</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-01-production-python/29-cicd-for-python-services.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">CI/CD for Python Services</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-02-llm-fundamentals/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 2 — LLM and Generative AI Fundamentals</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/01-how-ml-and-neural-networks-work.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How Machine Learning and Neural Networks Work</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/02-tensors-and-pytorch.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tensors and PyTorch</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/03-forward-pass-and-backpropagation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Forward Pass and Backpropagation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/04-attention-and-self-attention.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Attention and Self-Attention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/05-the-transformer-architecture.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Transformer Architecture</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/06-tokenization-and-tokens.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tokenization and Tokens</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/07-embeddings.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Embeddings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/08-context-windows-and-kv-cache.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Windows and the KV Cache</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/09-logits-softmax-next-token-prediction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Logits, Softmax, and Next-Token Prediction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/10-sampling-temperature-top-k-top-p.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Sampling: Temperature, Top-K, Top-P</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/11-training-vs-inference-and-batching.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Training vs Inference and Batching</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/12-pretraining-finetuning-instruction-tuning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pretraining, Fine-Tuning, and Instruction Tuning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/13-rlhf-and-preference-alignment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RLHF and Preference Alignment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/14-lora-qlora-peft.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Parameter-Efficient Fine-Tuning: LoRA, QLoRA, PEFT</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/15-numeric-precision-and-quantization.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Numeric Precision and Quantization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/16-structured-outputs-and-json-schema.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Structured Outputs and JSON Schema</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/17-function-and-tool-calling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Function and Tool Calling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/18-streaming-responses.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Streaming Responses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/19-prompt-design-and-system-prompts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Prompt Design and System Prompts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/20-context-engineering.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Engineering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/21-hallucinations.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hallucinations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/22-prompt-injection-and-context-poisoning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Prompt Injection and Context Poisoning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/23-model-comparison-and-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Model Comparison and Selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/24-provider-apis-openai-anthropic-gemini.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Provider APIs: OpenAI, Anthropic, Gemini</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-02-llm-fundamentals/25-open-source-models-and-hugging-face.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Open-Source Models and Hugging Face</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-03-rag-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 3 — RAG Engineering</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/01-rag-architecture.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Architecture</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/02-document-ingestion-and-parsing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Document Ingestion and Parsing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/03-chunking-strategies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chunking Strategies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/04-metadata-extraction-and-filtering.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Metadata Extraction and Filtering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/05-embedding-models-and-dimensions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Embedding Models and Dimensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/06-similarity-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Similarity Metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/07-vector-databases-and-ann-indexes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Vector Databases and ANN Indexes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/08-postgresql-pgvector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">PostgreSQL pgvector</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/09-dense-and-sparse-retrieval.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dense and Sparse Retrieval</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/10-hybrid-search.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Hybrid Search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/11-query-transformation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Query Transformation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/12-reranking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reranking</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/13-context-construction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Context Construction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/14-citations-and-grounded-generation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Citations and Grounded Generation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/15-knowledge-base-versioning.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Knowledge-Base Versioning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/16-rag-caching-and-latency.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Caching and Latency</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/17-retrieval-metrics.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Retrieval Metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/18-generation-quality-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Generation Quality Metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/19-rag-evaluation-and-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Evaluation and Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/20-multi-tenant-rag.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Multi-Tenant RAG</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-03-rag-engineering/21-rag-security-and-access-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">RAG Security and Access Control</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../phase-04-agentic-ai-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phase 4 — Agentic AI Engineering</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/01-what-an-ai-agent-is.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">What an AI Agent Is</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/02-the-agent-loop.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Agent Loop</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/03-tool-execution-and-result-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tool Execution and Result Validation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/04-agent-memory-short-term-and-working.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Agent Memory: Short-Term and Working</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/05-agent-memory-long-term-episodic-semantic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Agent Memory: Long-Term, Episodic, and Semantic</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/06-planning-decomposition-and-routing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Planning, Decomposition, and Routing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/07-reflection-and-self-correction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reflection and Self-Correction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/08-retries-termination-and-loop-detection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Retries, Termination, and Loop Detection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/09-state-management-and-persistence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">State Management and Persistence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/10-checkpointing-and-durable-execution.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Checkpointing and Durable Execution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/11-human-in-the-loop-and-approvals.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Human-in-the-Loop and Approvals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/12-guardrails.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Guardrails</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/13-structured-agent-outputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Structured Agent Outputs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/14-tool-schemas-and-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tool Schemas and Selection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/15-tool-permissions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tool Permissions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/16-parallel-and-conditional-workflows.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Parallel and Conditional Workflows</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/17-long-running-and-background-agents.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Long-Running and Background Agents</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/18-langgraph-graphs-and-state.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">LangGraph: Graphs and State</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/19-langgraph-checkpoints-interrupts-subgraphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">LangGraph: Checkpoints, Interrupts, and Subgraphs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/20-openai-agents-sdk.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">OpenAI Agents SDK</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/21-agent-orchestration-patterns.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Agent Orchestration Patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../phase-04-agentic-ai-engineering/22-agent-reliability.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Agent Reliability</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#why-this-exists" id="toc-why-this-exists" class="nav-link active" data-scroll-target="#why-this-exists">Why this exists</a></li>
  <li><a href="#start-from-zero" id="toc-start-from-zero" class="nav-link" data-scroll-target="#start-from-zero">Start from zero</a></li>
  <li><a href="#the-core-idea" id="toc-the-core-idea" class="nav-link" data-scroll-target="#the-core-idea">The core idea</a></li>
  <li><a href="#how-it-works" id="toc-how-it-works" class="nav-link" data-scroll-target="#how-it-works">How it works</a></li>
  <li><a href="#the-syntax-you-will-use" id="toc-the-syntax-you-will-use" class="nav-link" data-scroll-target="#the-syntax-you-will-use">The syntax you will use</a></li>
  <li><a href="#examples-simple-to-real" id="toc-examples-simple-to-real" class="nav-link" data-scroll-target="#examples-simple-to-real">Examples: simple to real</a></li>
  <li><a href="#in-production" id="toc-in-production" class="nav-link" data-scroll-target="#in-production">In production</a></li>
  <li><a href="#interview-questions" id="toc-interview-questions" class="nav-link" data-scroll-target="#interview-questions">Interview questions</a></li>
  <li><a href="#remember-this" id="toc-remember-this" class="nav-link" data-scroll-target="#remember-this">Remember this</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../phase-03-rag-engineering/index.html">Phase 3 — RAG Engineering</a></li><li class="breadcrumb-item"><a href="../phase-03-rag-engineering/17-retrieval-metrics.html"><span class="chapter-title">Retrieval Metrics</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Retrieval Metrics</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><strong>Interview answer (say this first).</strong> Retrieval metrics score how well search returns the right documents. <strong>Recall@K</strong> asks “did we get all the relevant documents into the top K?”; <strong>Precision@K</strong> asks “how many of the top K were relevant?”; <strong>MRR</strong> scores where the <em>first</em> relevant document appears; <strong>MAP</strong> and <strong>NDCG</strong> score the whole ranking. For RAG, recall comes first: if the evidence is not in the retrieved context, no prompt engineering can save the answer.</p>
</blockquote>
<section id="why-this-exists" class="level2">
<h2 class="anchored" data-anchor-id="why-this-exists">Why this exists</h2>
<p>You change the chunk size, swap the embedding model, add hybrid search, or turn on a reranker. Did the system get better or worse? Without a number, you are guessing.</p>
<p>Guessing fails in a specific way. The demo query looks fine, so you ship. Then a user asks something slightly different, retrieval returns a document about the wrong product, and the model confidently answers from it. Nobody notices until a customer does.</p>
<p>Consider a tiny failure. A user asks “how long is the refund window?” Your retriever returns five chunks in this order:</p>
<pre class="text"><code>1. shipping policy
2. refund policy          &lt;- relevant, but second
3. contact page
4. warranty terms
5. privacy policy</code></pre>
<p>The relevant chunk is at rank 2. The model may still answer correctly, but the correct evidence is competing with four irrelevant chunks. If the context window only fits the first chunk, the answer is wrong. <strong>Rank matters, not just presence.</strong></p>
<p>A single metric cannot describe this. You need a family:</p>
<ul>
<li>Did the relevant document appear at all? (<strong>Recall</strong>)</li>
<li>Was it near the top, or buried? (<strong>MRR</strong>, <strong>NDCG</strong>)</li>
<li>How much noise came with it? (<strong>Precision</strong>)</li>
<li>Across many questions, or just this one? (<strong>Mean</strong> of the above)</li>
</ul>
<p>Retrieval metrics exist to turn “it seems better” into a repeatable number you can put in a pull request.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The one-sentence purpose.</strong> Retrieval metrics measure whether the right evidence reached the model’s context, and where in the ranking it sat.</p>
</div>
</div>
</section>
<section id="start-from-zero" class="level2">
<h2 class="anchored" data-anchor-id="start-from-zero">Start from zero</h2>
<p>Every word below is used later on this page. Read this table first.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Word</th>
<th>Plain meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Retrieval</strong></td>
<td>Finding documents that answer a query. The search half of RAG.</td>
</tr>
<tr class="even">
<td><strong>Corpus</strong></td>
<td>The full collection of documents you can search.</td>
</tr>
<tr class="odd">
<td><strong>Document</strong></td>
<td>One item in the corpus, usually a chunk of a larger file.</td>
</tr>
<tr class="even">
<td><strong>Query</strong></td>
<td>The user’s question, or a transformed version of it.</td>
</tr>
<tr class="odd">
<td><strong>Ranking</strong></td>
<td>The retriever’s output: documents in order, best guess first.</td>
</tr>
<tr class="even">
<td><strong>Rank</strong></td>
<td>The position in that list. Rank 1 is the first result, rank 5 is the fifth.</td>
</tr>
<tr class="odd">
<td><strong>K</strong></td>
<td>How many top results you look at. <code>@5</code> means “in the first five”.</td>
</tr>
<tr class="even">
<td><strong>Relevant</strong></td>
<td>A document that truly contains the evidence needed to answer.</td>
</tr>
<tr class="odd">
<td><strong>Golden set</strong></td>
<td>A labelled list of queries, each with its known relevant documents. Also called a <em>ground-truth set</em>.</td>
</tr>
<tr class="even">
<td><strong>Label</strong></td>
<td>The human (or carefully checked) judgement that a document is relevant to a query.</td>
</tr>
<tr class="odd">
<td><strong>Binary relevance</strong></td>
<td>The label is only relevant (1) or not (0).</td>
</tr>
<tr class="even">
<td><strong>Graded relevance</strong></td>
<td>The label is a level, such as 0 = irrelevant, 1 = useful, 2 = highly relevant.</td>
</tr>
<tr class="odd">
<td><strong>True positive</strong></td>
<td>A relevant document that the retriever returned in the top K.</td>
</tr>
<tr class="even">
<td><strong>False positive</strong></td>
<td>An irrelevant document that the retriever returned in the top K.</td>
</tr>
<tr class="odd">
<td><strong>False negative</strong></td>
<td>A relevant document that the retriever missed from the top K.</td>
</tr>
<tr class="even">
<td><strong>Metric</strong></td>
<td>A formula that turns a ranking into a single number.</td>
</tr>
<tr class="odd">
<td><strong>Macro-average</strong></td>
<td>Compute the metric per query, then average those numbers. Every query counts equally.</td>
</tr>
<tr class="even">
<td><strong>Micro-average</strong></td>
<td>Pool all hits and misses across queries first, then compute once. Bigger queries dominate.</td>
</tr>
<tr class="odd">
<td><strong>Candidate set</strong></td>
<td>The larger list (say 50 documents) that a reranker later narrows down.</td>
</tr>
<tr class="even">
<td><strong>Reranker</strong></td>
<td>A second model that reorders the candidate set for better precision.</td>
</tr>
</tbody>
</table>
<p>Two ideas cause most confusion, so fix them now:</p>
<ul>
<li><strong>Recall vs precision is about direction.</strong> Recall asks “of all relevant documents, how many did we find?” Precision asks “of the documents we returned, how many were relevant?” Recall cares about misses; precision cares about noise.</li>
<li><strong>Binary vs graded is about the label.</strong> Binary says relevant or not. Graded says <em>how</em> relevant, which lets a metric reward putting the best document first.</li>
</ul>
</section>
<section id="the-core-idea" class="level2">
<h2 class="anchored" data-anchor-id="the-core-idea">The core idea</h2>
<p>Think of a librarian asked for books on a topic. She walks into the stacks and brings back a pile.</p>
<ul>
<li><strong>Recall</strong> is whether the important books are somewhere in the pile.</li>
<li><strong>Precision</strong> is what fraction of the pile is actually on topic.</li>
<li><strong>Rank</strong> is whether the best book is on top or under the pile.</li>
<li><strong>NDCG</strong> is a score that rewards putting the <em>most</em> relevant books highest.</li>
</ul>
<p>This is exactly the RAG situation. The retriever is the librarian. The pile is the context sent to the model. A short context window plus a badly ranked pile equals a wrong answer.</p>
<p>The pipeline is short but has two distinct places to measure:</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    Q["Query"] --&gt; R["Retriever&lt;br/&gt;returns ranked list&lt;br/&gt;K = 50 candidates"]
    R --&gt; M1["Retrieval metrics&lt;br/&gt;Recall@K, Precision@K,&lt;br/&gt;MRR, MAP, NDCG"]
    R --&gt; RR["Reranker&lt;br/&gt;reorders to top 5"]
    RR --&gt; M2["Reranked metrics&lt;br/&gt;Precision@5, NDCG@5"]
    RR --&gt; C["Context to the LLM"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>The crucial rule is the one the diagram shows: <strong>the reranker can only reorder what the retriever already found.</strong> If the relevant document is not in the candidate set, reranking cannot invent it. So measure <strong>recall@candidate_K</strong> first, before you ever tune the reranker.</p>
<p>Each metric answers a different question:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Question it answers</th>
<th>Cares about order?</th>
<th>Uses grades?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Recall@K</td>
<td>Did we find all relevant documents in the top K?</td>
<td>No</td>
<td>No</td>
</tr>
<tr class="even">
<td>Precision@K</td>
<td>What fraction of the top K was relevant?</td>
<td>No</td>
<td>No</td>
</tr>
<tr class="odd">
<td>MRR</td>
<td>How high is the <em>first</em> relevant document?</td>
<td>Yes, only the first</td>
<td>No</td>
</tr>
<tr class="even">
<td>MAP</td>
<td>How good is precision at every relevant hit?</td>
<td>Yes</td>
<td>No</td>
</tr>
<tr class="odd">
<td>NDCG@K</td>
<td>Is the ranking ordered best-first?</td>
<td>Yes, fully</td>
<td>Yes (binary or graded)</td>
</tr>
</tbody>
</table>
</section>
<section id="how-it-works" class="level2">
<h2 class="anchored" data-anchor-id="how-it-works">How it works</h2>
<p>The mechanism is the same for every retrieval metric. Only step 4 changes.</p>
<ol type="1">
<li><p><strong>Build a golden set.</strong> Collect real questions. For each, decide which documents are relevant. Store them as document IDs, not raw text, so you can compare them to retrieved IDs.</p></li>
<li><p><strong>Run the retriever.</strong> For each question, get the ranked list of document IDs. Keep the full list; you will slice it at different K values.</p></li>
<li><p><strong>Convert the ranking into labels.</strong> Walk the ranking from rank 1. For each document, mark it <code>1</code> if it is in the relevant set, else <code>0</code>. For NDCG, replace <code>1</code> with the document’s grade.</p></li>
<li><p><strong>Compute the per-query metric.</strong> Apply the formula for the metric you want (below). A query with zero relevant documents has no denominator, so the metric is undefined: the convention used here is to return <code>None</code> and skip that query when averaging. Decide your convention and write it down.</p></li>
<li><p><strong>Average across queries.</strong> Take the mean of the per-query scores. This is the macro-average, and it is the number you report. One hard query should not be hidden by many easy ones.</p></li>
<li><p><strong>Report at several K values.</strong> A retriever often has high Recall@50 and low Recall@5. Both are true and both are useful: the first says “the evidence is reachable”, the second says “the evidence is near the top”.</p></li>
<li><p><strong>Act on the weakest number.</strong> Low recall means fix indexing or candidate generation. Low precision means add a reranker or filter. Low NDCG with good recall means the ranking order is wrong.</p></li>
</ol>
<p>Here are the formulas. <code>retrieved[:k]</code> means the first <code>k</code> items. <code>relevant</code> is the set of all relevant documents. <code>rel(i)</code> is 1 if the document at rank <code>i</code> is relevant, else 0.</p>
<p><strong>Recall@K</strong></p>
<pre class="text"><code>Recall@K = |relevant ∩ retrieved[:K]| / |relevant|</code></pre>
<p><strong>Precision@K</strong></p>
<pre class="text"><code>Precision@K = |relevant ∩ retrieved[:K]| / K</code></pre>
<p><strong>Reciprocal rank (per query), then mean = MRR</strong></p>
<pre class="text"><code>RR = 1 / rank of the first relevant document   (0 if none is found)
MRR = mean(RR) over all queries</code></pre>
<p><strong>Average precision (per query), then mean = MAP</strong></p>
<pre class="text"><code>AP = (1 / |relevant|) * Σ over ranks i where rel(i)=1 of Precision@i
MAP = mean(AP) over all queries</code></pre>
<p><strong>Discounted cumulative gain and its normalised form</strong></p>
<pre class="text"><code>DCG@K  = Σ from i=1 to K of (2^grade(i) - 1) / log2(i + 1)
IDCG@K = DCG@K of the best possible ordering (highest grades first)
NDCG@K = DCG@K / IDCG@K</code></pre>
<p>Two details worth knowing. First, the denominator of AP is the <strong>total</strong> number of relevant documents, even ones that were never retrieved. Missing a relevant document therefore lowers AP, which is why AP feels recall-like. Second, for binary relevance <code>(2^1 - 1) = 1</code>, so DCG becomes the simpler <code>Σ rel(i) / log2(i + 1)</code>. The <code>log2(i + 1)</code> term is the “discount”: a hit at rank 10 is worth far less than a hit at rank 1.</p>
</section>
<section id="the-syntax-you-will-use" class="level2">
<h2 class="anchored" data-anchor-id="the-syntax-you-will-use">The syntax you will use</h2>
<p>There is no library syntax for the formulas. These are short functions you own. The shapes below are the real forms used in evaluation code.</p>
<p><strong>Recall@K.</strong> Count hits in the top K, divide by the number of relevant documents.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> recall_at_k(retrieved, relevant, k):</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> relevant:</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">None</span>                 <span class="co"># zero-relevant query: skip, do not divide by zero</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    hits <span class="op">=</span> <span class="bu">sum</span>(<span class="dv">1</span> <span class="cf">for</span> d <span class="kw">in</span> retrieved[:k] <span class="cf">if</span> d <span class="kw">in</span> relevant)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> hits <span class="op">/</span> <span class="bu">len</span>(relevant)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Precision@K.</strong> Same numerator, but divide by K instead of by the number of relevant documents.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> precision_at_k(retrieved, relevant, k):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    hits <span class="op">=</span> <span class="bu">sum</span>(<span class="dv">1</span> <span class="cf">for</span> d <span class="kw">in</span> retrieved[:k] <span class="cf">if</span> d <span class="kw">in</span> relevant)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> hits <span class="op">/</span> k</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Reciprocal rank.</strong> Return as soon as you see the first relevant document. Return <code>0.0</code> when none is found, so the average is not skewed up.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> reciprocal_rank(retrieved, relevant):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, d <span class="kw">in</span> <span class="bu">enumerate</span>(retrieved, start<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> d <span class="kw">in</span> relevant:</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="fl">1.0</span> <span class="op">/</span> i</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="fl">0.0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Average precision.</strong> Add <code>Precision@i</code> at every rank <code>i</code> that is a relevant hit, then divide by the total number of relevant documents.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> average_precision(retrieved, relevant, k):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> relevant:</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">None</span>                 <span class="co"># zero-relevant query: skip, do not divide by zero</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    hits <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    total <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, d <span class="kw">in</span> <span class="bu">enumerate</span>(retrieved[:k], start<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> d <span class="kw">in</span> relevant:</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>            hits <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>            total <span class="op">+=</span> hits <span class="op">/</span> i          <span class="co"># Precision@i at this hit</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> total <span class="op">/</span> <span class="bu">len</span>(relevant)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>NDCG@K.</strong> Build the actual grade list and the ideal grade list (sorted descending), then divide the two DCGs. Reusing one <code>dcg</code> function guarantees the actual and ideal scores use the same formula.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> dcg(grades):</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sum</span>((<span class="dv">2</span> <span class="op">**</span> g <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> math.log2(i <span class="op">+</span> <span class="dv">1</span>) <span class="cf">for</span> i, g <span class="kw">in</span> <span class="bu">enumerate</span>(grades, <span class="dv">1</span>))</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ndcg_at_k(retrieved, grades, k):</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> grades:</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">None</span>                 <span class="co"># no relevant documents: IDCG would be zero</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    actual <span class="op">=</span> [grades.get(d, <span class="dv">0</span>) <span class="cf">for</span> d <span class="kw">in</span> retrieved[:k]]</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    ideal <span class="op">=</span> <span class="bu">sorted</span>(grades.values(), reverse<span class="op">=</span><span class="va">True</span>)[:k]</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> dcg(actual) <span class="op">/</span> dcg(ideal)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>grades</code> is a dictionary from document ID to relevance level. For binary relevance, build it as <code>{d: 1 for d in relevant}</code>. Documents that were retrieved but are not in <code>grades</code> get <code>0</code>. With no relevant documents the ideal gain is zero, so <code>ndcg_at_k</code> returns <code>None</code> rather than dividing by zero.</p>
<p><strong>Average the per-query scores.</strong> Macro-averaging is one call to <code>mean</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statistics <span class="im">import</span> mean</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>mrr <span class="op">=</span> mean(reciprocal_rank(q[<span class="st">"retrieved"</span>], q[<span class="st">"relevant"</span>]) <span class="cf">for</span> q <span class="kw">in</span> golden)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>All of this is standard library. No evaluation framework is required to start.</p>
</section>
<section id="examples-simple-to-real" class="level2">
<h2 class="anchored" data-anchor-id="examples-simple-to-real">Examples: simple to real</h2>
<p><strong>Example 1 — one query, by hand.</strong></p>
<p>Relevant documents are <code>{A, C}</code>. The retriever returns <code>[A, B, C, D, E]</code>.</p>
<pre class="text"><code>Recall@5    = 2 / 2 = 1.0        (both relevant documents found)
Precision@5 = 2 / 5 = 0.4        (two of five returned were relevant)
Precision@1 = 1 / 1 = 1.0        (the top result was relevant)</code></pre>
<p>Recall is perfect because both documents are in the top five. Precision is low because three irrelevant documents came along. This is the normal trade-off: larger K raises recall and lowers precision.</p>
<p><strong>Example 2 — where the first relevant document sits.</strong></p>
<p>Same relevant set <code>{A, C}</code>, but this time <code>A</code> is at rank 3:</p>
<pre class="text"><code>rank 1: X   (irrelevant)
rank 2: Y   (irrelevant)
rank 3: A   (relevant)  -&gt; RR = 1/3 = 0.3333
rank 4: C   (relevant)</code></pre>
<p><code>Recall@4</code> is still <code>2 / 2 = 1.0</code>, but <code>RR</code> dropped from <code>1.0</code> to <code>0.3333</code>. Recall cannot see rank; MRR can. This is exactly why you report more than one metric.</p>
<p><strong>Example 3 — binary NDCG rewards the top position.</strong></p>
<p>Relevant set <code>{A, C}</code>, retrieved <code>[A, B, C, D, E]</code>. Using binary grades (<code>A = 1</code>, <code>C = 1</code>):</p>
<pre class="text"><code>DCG@5  = 1/log2(2) + 0/log2(3) + 1/log2(4) + 0 + 0 = 1.0 + 0.5 = 1.5
IDCG@5 = 1/log2(2) + 1/log2(3)                      = 1.0 + 0.6309 = 1.6309
NDCG@5 = 1.5 / 1.6309 = 0.9197</code></pre>
<p>An NDCG of <code>0.92</code> means the ranking is close to ideal. If the retriever had returned <code>[B, A, C, D, E]</code> instead — pushing a relevant document down to rank 3 — the score would fall to <code>0.6934</code>: the discount is harsher at lower ranks, so order matters. Note that swapping the two equally-relevant documents, <code>[C, B, A, D, E]</code>, leaves NDCG unchanged at <code>0.9197</code>; NDCG only falls when a relevant document moves to a <em>lower</em> rank.</p>
<p><strong>Example 4 — graded NDCG.</strong></p>
<p>Graded labels say how relevant each document is: <code>A = 3</code> (best), <code>B = 2</code>, <code>D = 1</code>, <code>C = 0</code>. Retrieved order is <code>[A, B, C, D]</code>.</p>
<pre class="text"><code>DCG@4  = (2^3-1)/log2(2) + (2^2-1)/log2(3) + (2^0-1)/log2(4) + (2^1-1)/log2(5)
       = 7/1.0 + 3/1.585 + 0/2.0 + 1/2.322
       = 9.3235
IDCG@4 = (2^3-1)/log2(2) + (2^2-1)/log2(3) + (2^1-1)/log2(4) + (2^0-1)/log2(5)
       = 9.3928
NDCG@4 = 9.3235 / 9.3928 = 0.9926</code></pre>
<p>The only difference from the ideal is that grades 1 and 0 are swapped, which barely changes the score. Graded NDCG is the right metric when “somewhat relevant” is a real category, which is common in enterprise search.</p>
<p><strong>Example 5 — a three-query golden set, end to end.</strong></p>
<p>This is the script to run. It prints one row per query and the macro-average.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statistics <span class="im">import</span> mean</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> recall_at_k(retrieved, relevant, k):</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> relevant:</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sum</span>(<span class="dv">1</span> <span class="cf">for</span> d <span class="kw">in</span> retrieved[:k] <span class="cf">if</span> d <span class="kw">in</span> relevant) <span class="op">/</span> <span class="bu">len</span>(relevant)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> precision_at_k(retrieved, relevant, k):</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sum</span>(<span class="dv">1</span> <span class="cf">for</span> d <span class="kw">in</span> retrieved[:k] <span class="cf">if</span> d <span class="kw">in</span> relevant) <span class="op">/</span> k</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> reciprocal_rank(retrieved, relevant):</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, d <span class="kw">in</span> <span class="bu">enumerate</span>(retrieved, start<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> d <span class="kw">in</span> relevant:</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="fl">1.0</span> <span class="op">/</span> i</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="fl">0.0</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> average_precision(retrieved, relevant, k):</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> relevant:</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>    hits, total <span class="op">=</span> <span class="dv">0</span>, <span class="fl">0.0</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, d <span class="kw">in</span> <span class="bu">enumerate</span>(retrieved[:k], start<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> d <span class="kw">in</span> relevant:</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>            hits <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>            total <span class="op">+=</span> hits <span class="op">/</span> i</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> total <span class="op">/</span> <span class="bu">len</span>(relevant)</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> dcg(grades):</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">sum</span>((<span class="dv">2</span> <span class="op">**</span> g <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> math.log2(i <span class="op">+</span> <span class="dv">1</span>) <span class="cf">for</span> i, g <span class="kw">in</span> <span class="bu">enumerate</span>(grades, <span class="dv">1</span>))</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ndcg_at_k(retrieved, grades, k):</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> grades:</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>    actual <span class="op">=</span> [grades.get(d, <span class="dv">0</span>) <span class="cf">for</span> d <span class="kw">in</span> retrieved[:k]]</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>    ideal <span class="op">=</span> <span class="bu">sorted</span>(grades.values(), reverse<span class="op">=</span><span class="va">True</span>)[:k]</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> dcg(actual) <span class="op">/</span> dcg(ideal)</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>golden <span class="op">=</span> [</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"retrieved"</span>: [<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>, <span class="st">"E"</span>], <span class="st">"relevant"</span>: {<span class="st">"A"</span>, <span class="st">"C"</span>}},</span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"retrieved"</span>: [<span class="st">"C"</span>, <span class="st">"D"</span>, <span class="st">"B"</span>, <span class="st">"E"</span>, <span class="st">"A"</span>], <span class="st">"relevant"</span>: {<span class="st">"B"</span>}},</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"retrieved"</span>: [<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>, <span class="st">"E"</span>], <span class="st">"relevant"</span>: {<span class="st">"D"</span>, <span class="st">"E"</span>}},</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> q <span class="kw">in</span> golden:</span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>    r, rel <span class="op">=</span> q[<span class="st">"retrieved"</span>], q[<span class="st">"relevant"</span>]</span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>    grades <span class="op">=</span> {d: <span class="dv">1</span> <span class="cf">for</span> d <span class="kw">in</span> rel}</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="bu">round</span>(recall_at_k(r, rel, K), <span class="dv">4</span>), <span class="bu">round</span>(precision_at_k(r, rel, K), <span class="dv">4</span>),</span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>          <span class="bu">round</span>(reciprocal_rank(r, rel), <span class="dv">4</span>), <span class="bu">round</span>(average_precision(r, rel, K), <span class="dv">4</span>),</span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>          <span class="bu">round</span>(ndcg_at_k(r, grades, K), <span class="dv">4</span>))</span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"MEAN"</span>,</span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a>      <span class="bu">round</span>(mean(recall_at_k(q[<span class="st">"retrieved"</span>], q[<span class="st">"relevant"</span>], K) <span class="cf">for</span> q <span class="kw">in</span> golden), <span class="dv">4</span>),</span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a>      <span class="bu">round</span>(mean(precision_at_k(q[<span class="st">"retrieved"</span>], q[<span class="st">"relevant"</span>], K) <span class="cf">for</span> q <span class="kw">in</span> golden), <span class="dv">4</span>),</span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a>      <span class="bu">round</span>(mean(reciprocal_rank(q[<span class="st">"retrieved"</span>], q[<span class="st">"relevant"</span>]) <span class="cf">for</span> q <span class="kw">in</span> golden), <span class="dv">4</span>),</span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a>      <span class="bu">round</span>(mean(average_precision(q[<span class="st">"retrieved"</span>], q[<span class="st">"relevant"</span>], K) <span class="cf">for</span> q <span class="kw">in</span> golden), <span class="dv">4</span>),</span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a>      <span class="bu">round</span>(mean(ndcg_at_k(q[<span class="st">"retrieved"</span>], {d: <span class="dv">1</span> <span class="cf">for</span> d <span class="kw">in</span> q[<span class="st">"relevant"</span>]}, K) <span class="cf">for</span> q <span class="kw">in</span> golden), <span class="dv">4</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Output (verified):</p>
<pre class="text"><code>1.0 0.4 1.0 0.8333 0.9197
1.0 0.2 0.3333 0.3333 0.5
1.0 0.4 0.25 0.325 0.5013
MEAN 1.0 0.3333 0.5278 0.4972 0.6403</code></pre>
<p>Read it like this. <strong>Recall@5 is 1.0 for every query</strong>, so the candidate set always contains the evidence; the retriever is not the bottleneck here. <strong>Precision@5 is 0.33</strong>, so two thirds of the context is noise, and a reranker would help. <strong>MRR is 0.53</strong> because in two of three queries the first relevant document is at rank 3 and 4. <strong>NDCG@5 is 0.64</strong>, the same story with a full-ranking penalty. <strong>MAP is 0.50</strong>, pulled down by query 3, where both relevant documents sit near the bottom.</p>
<p>That is the whole point of the metric family: each number points at a different fix.</p>
</section>
<section id="in-production" class="level2">
<h2 class="anchored" data-anchor-id="in-production">In production</h2>
<ul>
<li><strong>Recall first, precision second.</strong> A missing document is unfixable by the model; an extra document is noise the model can often ignore. Tune recall on the candidate set, then tune precision with a reranker.</li>
<li><strong>Measure recall at the candidate K, not just the final K.</strong> If you retrieve 50 and rerank to 5, compute Recall@50. Recall@5 after reranking is bounded by Recall@50 and hides retriever misses.</li>
<li><strong>Golden sets rot.</strong> Documents are re-indexed, IDs change, and old labels go stale. Version the golden set with the corpus and re-check it on every index rebuild.</li>
<li><strong>You need enough queries for the mean to be stable.</strong> Five queries cannot distinguish two retrievers; differences of a few points are noise. Aim for dozens to hundreds, with hard and easy questions mixed.</li>
<li><strong>Keep a hard slice.</strong> Average hides failures. Report the overall number <strong>and</strong> a breakdown by query type (exact lookup, multi-hop, acronym, no-answer) so a regression in one slice is visible.</li>
<li><strong>Do not label with the system you are testing.</strong> Using retriever output to build the golden set guarantees a high score and proves nothing. Labels must be independent, ideally human-checked.</li>
<li><strong>Beware duplicate documents.</strong> Near-identical chunks mean the “second” relevant result may be the same text again. Deduplicate before scoring, or Precision and NDCG will look better than the context really is.</li>
<li><strong>Decide how to treat no-answer queries.</strong> Some questions have no relevant document, so recall, AP, and NDCG have no denominator. The guarded functions above return <code>None</code> for these and the evaluation loop skips them; alternatively define them as always-correct. Either way, be consistent, because the convention changes the score.</li>
<li><strong>Micro vs macro matters with uneven labels.</strong> If one query has 20 relevant documents, micro-averaging lets it dominate. For RAG, macro-average is usually the honest choice.</li>
<li><strong>Recall has a ceiling that is not 1.0.</strong> If your labels are incomplete, recall is capped and you will chase a phantom. Audit a sample of “misses” by hand before believing a low score.</li>
<li><strong>Test both the recovered ranking and the final one.</strong> Log metrics at the retriever and at the reranker so you can attribute a change to the right stage.</li>
<li><strong>Never tune on the test set.</strong> Split the golden set into a tuning part and a held-out part, or the reported number becomes a memory of your own choices.</li>
</ul>
</section>
<section id="interview-questions" class="level2">
<h2 class="anchored" data-anchor-id="interview-questions">Interview questions</h2>
<section id="why-is-recall-usually-the-most-important-retrieval-metric-for-rag" class="level3">
<h3 class="anchored" data-anchor-id="why-is-recall-usually-the-most-important-retrieval-metric-for-rag">1. Why is recall usually the most important retrieval metric for RAG?</h3>
<p><strong>Answer.</strong> Because generation can only use what retrieval returns. If the relevant document is not in the context, the model either says it does not know or hallucinates. Recall directly measures the presence of evidence. Precision affects how much noise competes for attention, which matters, but a precision problem is survivable while a recall problem is usually fatal.</p>
<p><strong>Follow-up: “Can high precision compensate for low recall?”</strong> No.&nbsp;Precision only describes the documents you did return. A retriever that returns one correct document and nothing else has perfect precision and terrible recall on a query with five relevant documents.</p>
<p><strong>Trap.</strong> Optimising precision because it is easy to move with a reranker, then declaring success while recall stays low. Always check the candidate-set recall before trusting the reranked result.</p>
</section>
<section id="what-is-the-difference-between-recallk-and-precisionk" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-difference-between-recallk-and-precisionk">2. What is the difference between Recall@K and Precision@K?</h3>
<p><strong>Answer.</strong> Recall@K is hit count divided by the <em>total number of relevant documents</em>, so it measures coverage. Precision@K is hit count divided by <em>K</em>, so it measures how clean the returned list is. Recall rises as K grows; precision usually falls. Report both because they can move in opposite directions.</p>
<p><strong>Follow-up: “Which one does the user feel?”</strong> Precision, in a single-result UI. A user who sees one answer cares that it is correct, not that four other relevant documents existed. Recall matters for the downstream model that needs complete evidence.</p>
<p><strong>Trap.</strong> Dividing recall by K. That denominator is the number of relevant documents, which can be larger or smaller than K. Using K by mistake makes Recall@10 of a query with three relevant documents look artificially low.</p>
</section>
<section id="what-does-mrr-measure-and-when-is-it-the-wrong-metric" class="level3">
<h3 class="anchored" data-anchor-id="what-does-mrr-measure-and-when-is-it-the-wrong-metric">3. What does MRR measure, and when is it the wrong metric?</h3>
<p><strong>Answer.</strong> MRR is the mean of <code>1 / rank</code> of the first relevant document per query. It rewards putting <em>some</em> relevant result high. It is right for a single-answer task, like a question-answering bot that reads only the top result. It is wrong for RAG that needs several documents, because it ignores all relevant documents after the first.</p>
<p><strong>Follow-up: “How do MRR and MAP differ?”</strong> MRR only looks at the first hit. MAP looks at every relevant hit and rewards having all of them high in the list. For multi-document context, MAP or NDCG is more informative.</p>
<p><strong>Trap.</strong> Forgetting the zero case. If no relevant document is retrieved, the reciprocal rank is <code>0.0</code>. Dividing by 1 or skipping the query would inflate the average.</p>
</section>
<section id="explain-ndcg-and-why-the-logarithm-is-there." class="level3">
<h3 class="anchored" data-anchor-id="explain-ndcg-and-why-the-logarithm-is-there.">4. Explain NDCG and why the logarithm is there.</h3>
<p><strong>Answer.</strong> NDCG is discounted cumulative gain divided by the ideal gain. You gain for each document based on its relevance grade, discounted by <code>log2(rank + 1)</code>, because a relevant document near the top is more useful than the same document at rank 20. Dividing by the ideal ordering normalises the score to between 0 and 1 so queries with different labels are comparable.</p>
<p><strong>Follow-up: “Why <code>2^grade - 1</code> instead of just grade?”</strong> The exponential gain makes high grades disproportionately valuable, which matches tasks where the single best document matters much more than several mildly useful ones. With binary grades the two forms are identical.</p>
<p><strong>Trap.</strong> Forgetting to normalise. Raw DCG is not comparable across queries because a query with many relevant documents has a larger maximum. Always divide by IDCG.</p>
</section>
<section id="what-is-map-and-how-is-it-different-from-mrr" class="level3">
<h3 class="anchored" data-anchor-id="what-is-map-and-how-is-it-different-from-mrr">5. What is MAP, and how is it different from MRR?</h3>
<p><strong>Answer.</strong> Average precision averages <code>Precision@i</code> over every rank where a relevant document appears, then divides by the total number of relevant documents. MAP is the mean of AP across queries. Unlike MRR, it accounts for all relevant documents and their positions, so it is a ranking-quality metric for multi-document retrieval.</p>
<p><strong>Follow-up: “Why divide AP by the total relevant count rather than the number retrieved?”</strong> Because unretrieved relevant documents must count as misses. Dividing by the number found would let a retriever score perfectly by returning only one document out of five.</p>
<p><strong>Trap.</strong> Computing AP over only the top K and forgetting that <code>|relevant|</code> may exceed K. With K smaller than the relevant count, even a perfect top K cannot reach AP of 1.0, which is correct and important.</p>
</section>
<section id="how-do-you-choose-k" class="level3">
<h3 class="anchored" data-anchor-id="how-do-you-choose-k">6. How do you choose K?</h3>
<p><strong>Answer.</strong> Match K to the context budget and the task. For a question-answering system, the final K is however many chunks fit the prompt, often 3 to 10. For candidate generation before reranking, use a larger K, often 50 to 100, and measure recall there. Pick the smallest candidate K that keeps recall high; anything beyond that is reranker work that a reranker can do better.</p>
<p><strong>Follow-up: “What does the recall curve look like as K grows?”</strong> It rises quickly, then flattens at a ceiling set by your retriever and labels. If recall is still climbing steeply at your K, increase K or improve the candidate retriever. If it has flattened and is below target, the problem is in indexing or the query, not K.</p>
<p><strong>Trap.</strong> Reporting only one K. A single number hides whether the evidence is absent or merely ranked low. Always report at least a small K and a large K.</p>
</section>
<section id="binary-versus-graded-relevance-when-do-you-use-each" class="level3">
<h3 class="anchored" data-anchor-id="binary-versus-graded-relevance-when-do-you-use-each">7. Binary versus graded relevance: when do you use each?</h3>
<p><strong>Answer.</strong> Use binary when a document either answers the question or does not, which is typical for a single-fact lookup. Use graded relevance when quality is a spectrum, typically 0 to 3, which is typical for enterprise search where a document can be partly on topic. Graded labels carry more information, so NDCG can reward the best document; binary labels are cheaper to collect and easier to agree on.</p>
<p><strong>Follow-up: “What is the cost of graded labels?”</strong> Annotators disagree more, so you need clear guidelines and more than one labeller for the tricky levels. Binary labels converge faster and cost less.</p>
<p><strong>Trap.</strong> Using graded NDCG with binary labels and then wondering why it behaves like a simple hit count. The gain formula only shows its value when grades differ.</p>
</section>
<section id="how-do-these-metrics-help-you-debug-a-bad-rag-answer" class="level3">
<h3 class="anchored" data-anchor-id="how-do-these-metrics-help-you-debug-a-bad-rag-answer">8. How do these metrics help you debug a bad RAG answer?</h3>
<p><strong>Answer.</strong> They localise the fault. If Recall@candidate_K is low, the evidence never reached the model: fix the index, chunking, embeddings, or query transformation. If recall is high but Precision@K or NDCG is low, the evidence is present but buried among noise: add a reranker. If retrieval metrics are good and answers are still wrong, the fault is in generation, not retrieval. That single split is the most valuable debugging step.</p>
<p><strong>Follow-up: “What if recall is high but users still complain?”</strong> Then the answer is a generation or context-assembly problem: the model is ignoring the evidence, the context is too long, or the prompt is unclear. Move to generation metrics like faithfulness and answer relevance.</p>
<p><strong>Trap.</strong> Starting with prompt changes when the retrieved context never contained the answer. Always check retrieval first, because it is cheaper to measure and easier to fix.</p>
</section>
</section>
<section id="remember-this" class="level2">
<h2 class="anchored" data-anchor-id="remember-this">Remember this</h2>
<ul>
<li><strong>Recall = coverage, precision = cleanliness.</strong> Recall asks “did we find it?”, precision asks “was the list clean?”.</li>
<li><strong>Rank matters.</strong> MRR, MAP, and NDCG reward putting relevant documents near the top; Recall@K cannot see order.</li>
<li><strong>Measure recall at the candidate K.</strong> A reranker can only reorder what retrieval already found.</li>
<li><strong>NDCG = DCG / IDCG</strong>, with gain <code>2^grade - 1</code> discounted by <code>log2(rank + 1)</code>.</li>
<li><strong>Average over queries (macro), report several K, and keep a held-out set</strong> so the number means something.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ranjeet-h\.github\.io\/agentic-ai-engineer-book");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../phase-03-rag-engineering/16-rag-caching-and-latency.html" class="pagination-link" aria-label="RAG Caching and Latency">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">RAG Caching and Latency</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../phase-03-rag-engineering/18-generation-quality-metrics.html" class="pagination-link" aria-label="Generation Quality Metrics">
        <span class="nav-page-text"><span class="chapter-title">Generation Quality Metrics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>